### ISSUE TITLE
TCAP statistics enhancement

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#117]
Hello @vetss ,

I'd like to discuss a feature extracted from our Jss7 fork:

Topic: Support external statistics of TCAP events
Type: Enhancement
Issue short: Add possibility to register custom stat listeners to TCAP stacks

Description: While the JSs7 library has a built-in tcap statistics module, applications using the library might have its own statisctic module or special requirements that the built-in module does not satisfy. To support the extensibility of the TCAP statistics a new TCAPCounterProviderImplListener interface is introduced. It can be registered to the TCAPCounterProviderImpl which propagates the statistic events by calling the appropiate callback of the new listener interface.

I'll also provide a corresponding PR so you can review the proposed implementation too.
If you decide that you'll merge this feature then I'll prepare a PR for the TCAP ANSI stack too.

Thanks for reviewing.

Best Regards,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

I think that the idea of usage of a customer listner for statistic eventr in TCAPCounterProviderImpl is reasonable. But the design of implementation is not fully proper.

I think a better way is:
- rename TCAPCounterProviderImplListener to TCAPCounterEventsListener and move it to the api section
- have only one TCAPCounterEventsListener (not a list) to simplify this and keep it at TCAPStack
- have setter and getter TCAPCounterEventsListener at the stack level and keep TCAPCounterEventsListener at the stack class to avoid of destroying of it when stacj restart. TCAPCounterProviderImpl will reuse TCAPCounterEventsListener instanse from stack.

**Comment by vetss** [comment]
This ticket is fixed by PR: https://github.com/RestComm/jss7/pull/157
