### ISSUE TITLE
TCAP dialog getter/setter for idle task timeout

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#119]
Hello,

In our project we have to be able to set idle task timeout at Dialog level. It is because we have multiple CAP modules (one for every phase) using the same TCAP stack and the  value of idle task timeout can be configured in CAP (and MAP) modules. 
Therefore we expose the value of idle task timeout of the TCAP dialog by adding getter and setter methods to the Dialog interfaces in TCAP, CAP and MAP modules. I'll send a PR containing this feature.
Please, consider if you need this modification or not and also create an issue for TCAP ANSI module if you think this feature is fit to there too.

Thank you!
Brgds,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

I have committed your update:
https://github.com/RestComm/jss7/commit/c9aca80856723784b58840d5651ffa3e342c5755
