### ISSUE TITLE
Topic: Implementing some API features in CAP InitialDPRequestImpl

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#125]
Hello,

I extracted the following feautres from our JSs7 fork:
-
Topic: Implementing some API features in CAP InitialDPRequestImpl
Description: 
Added the missing ASN.1/XML encoding/decoding implementation for
some parameters in InitialDPRequestImpl.

Added the missing ASN.1/XML encoding/decoding implementation for
most of the parameters in InitialDPArgExtensionImpl.

Added utility methods to OctetStringBase to allow subclasses to
easily read/write their byte[] data as hex strings to/from XML.
-
I'll attach a PR to this issue please review it.

Thanks!

Best Regards,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

I have fixed your topic by this commit:
https://github.com/RestComm/jss7/commit/ec420c2b2c6726b7d496a6fa19e8a2ba2e4aa16d
(I failed to add your commits directly)

I have not added changing of capVersion boolean->enum to keep a backword compatibility
Thanks for your work

**Comment by AlerantAppNGIN** [comment]
Hi @vetss,

Thank you for sharing us the above code example. 
We are thinking of changing our interface between IM-SCF and Application servers to increase its flexibility and compatibility with existing systems. So your ideas felt on a fertile ground, so to speak :-)

I think we can agree that we only serialize CAP version in a primitive if it is used in its encoding/decoding logic. 

Brgds,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

ok, thanks for your update
