### ISSUE TITLE
CAP FCI SMS xml serialization

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#127]
Hello,

I'd like to add XML serialization to the class that implement the FCI SMS function.
I'll send a PR to this issue.

Best Regards,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

I have accepted your update into a single commit (into netty-2 branch):
https://github.com/RestComm/jss7/commit/d52abc911a902c01c73f9be87f49ec761cddbce9

Thank for your work.

1) when you implement (de)serializing take into account that some paramentes may be null and yuo need to check it in code
2) may I ask you to make your PR as a change to netty-2 branch and make them as isolated commit / work (your PR contains now 5 commints) to simplify my work ?
3) we need to implement 2 unit tests for checking of XML serializing. Please finish this work.

**Comment by vetss** [comment]
Missed part is:
- adding of unit tests for serializing 
  - for FCIBCCCAMELsequence1SMSImpl 
  - FurnishChargingInformationSMSRequestImpl

**Comment by vetss** [comment]
Hello @agafox 

sorry for delayed response. I have committed your update and marked an operation as it has a support for XML serializing.

Final Fixing by:
https://github.com/RestComm/jss7/commit/bd44f0b486292c9712f99131c900aa96cf9aa55c
https://github.com/RestComm/jss7/commit/6d92e4b378848b9c524af804a9370efd719af561
