### ISSUE TITLE
SCCP doesn't respect point-code for incoming message

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#13]
Suppose SCCP stack is configured with multiple rsp and SCCP Rule1 configured to use PC1 as primary and PC2 as secondary. Now if message received from PC2 and consumed by SCCP-User and replies back, the GT matches for Rule1, it will use PC1 for out going message instead of PC2.

We need to make a discussion firstly how it is better to achieve this task

**Comment by vetss** [comment]
The described case is needed for more thinking if it is a bug or not.

**Comment by faizann** [comment]
Hi
I think this is a normal behaviour in the network. The M3UA layer is transaction agnostic and hence pointcodes/addresses should be decided based on SCCP rules (loadsharing/dominant/solitary).

This can be an issue only when the services like USSD/SMSCs are not behind STPs which means that users need to rethink their network implementation.
