### ISSUE TITLE
Enable/Disable configuration persistance

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#130]
Hello,

The RestComm JSs7 library has its own solution for storing and loading its configuration to/from XML files. It is an important feature of the stack but when JSs7 used as a library it is very likely that the application based-on the library has its own configuration management . Which makes the JSs7 own configuration handling redundant. I think it would be a good idea if we make configurable if the Jss7 stack persist is configuration or not. 
Please, tell me what do you think about this.
Thank you!

Brgds,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

I think it is reasonable to add into each JSS7 / SCTP stack an extra setter via which we can force not to store / load parameters. For backword compatibility this option must have a default value "perfom of storing/loading config data".

Like this:
void setAvoidConfigUsage(boolean val);
boolean getAvoidConfigUsage();

So in this case you will be able to set this parameter after stack creation before it is going to get started.
Do you want to contribute it ?

**Comment by AlerantAppNGIN** [comment]
Hello @vetss ,

I'd like to contribute to the implementation of this feature. But I have to postpone this task until our other open issues are solved. If it can wait a few weeks then you can assign this issue to me.

Thanks,
Gabor

**Comment by vetss** [comment]
Hi @AlerantAppNGIN 

it can wait for some time.

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

are you able to provide the update ?

**Comment by vetss** [comment]
Hello @knosach 

I reopen the issue becuase IMO it is wrong implemented. Adding of new classes for just a simple case for 
storing/nonstoring of stack parameters introduces an extra complexity. Usage of an extra stack parameters like `setAvoidConfigUsage(boolean val);` will be simplier. Let's revert your commit and make the described implementation.

PS1: for SCCP stack classes we can add only one `AvoidConfigUsage` parameter only for SccpStackImpl class and other sccp classes like SccrResources etc
PS2: We have this file https://github.com/RestComm/jss7/blob/master/Stacks_Parameters.ods with description of stack parameters, we need to update it with meaning of added parameters.

**Comment by knosach** [comment]
Currently, we have already the implementation of it https://github.com/RestComm/jss7/commit/a39cd1b7c46ec2d7db5f020443119dead47db7e2 if we need other implementation we can create the new one
