### ISSUE TITLE
Docs: Mention MAP and CAP specification version

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#144]
User Guide: chapters: "12. MAP" and "13. CAP"

**Comment by knosach** [comment]
Currently SS7 implement CAP version 10.0.0 except two packets:
* `entityReleased`
* `playTone`
from version 11.0.0 modified headers of `releaseCall`

**Comment by vetss** [comment]
MAP
- we support MAP versions 1, 2, 3, 4 with java interfaces for a version 3GPP TS 29.002 V10.3.0 (2011-06)
- the latest spec version is 3GPP TS 29.002 V15.1.0 (2017-09) that contains interafaces updates (PS: there are many example of it)

CAP
- we support CAP versions 1, 2, 3, 4 with java interfaces for a version V11.0.0 (2011-09)
- the latest spec version is V14.0.0 (2017-03) that possible contains interafaces updates (PS: I have not found changes from a firts check, but the most probably we have them)

List of implemented operations and parameters can be found there:
https://github.com/RestComm/jss7/blob/sccp-co/map/MAPMessagesImplemented.ods
https://github.com/RestComm/jss7/blob/sccp-co/cap/CAPMessagesImplemented.ods
https://github.com/RestComm/jss7/blob/sccp-co/isup/ISUPMessagesImplemented.ods

Specifications for TCAP, SCCP, ISUP were not changed from implemenation time and we can say that we implemeted the latest spec
INAP - we do not have an implementation of it
