### ISSUE TITLE
Uncertain Java language level for project

### ISSUE THREAD

**Issue by raidan2** [RestComm/jss7#149]
According to Java language specification 1.5 it's not possible to use annotation **@Override** over implemented (interface) methods like
```
    @Override
    public Long addApplyChargingReportRequest(TimeDurationChargingResult timeDurationChargingResult) throws CAPException {
        return addApplyChargingReportRequest(_Timer_Default, timeDurationChargingResult);
    }
```
at **org.mobicents.protocols.ss7.cap.service.circuitSwitchedCall.CAPDialogCircuitSwitchedCallImpl** for example.

This could be possible in 1.6 and later.

This issue is avoided by latest Java compilers (IDEA will blow in reds until you manually switch each project to Java 6).

However, is it really worth it to support Java 5 still?

**Comment by deruelle** [comment]
No we don't support Java 5 anymore

**Comment by vetss** [comment]
Hi @raidan2 

> However, is it really worth it to support Java 5 still?

Java 5 does not support SCTP for m3ua so usage of this version is useless. Really we support only Java 7. Java 8 is not yet supported because of uncompatibly with jboss 5.1. Support of Java 8 is a task for future.

**Comment by raidan2** [comment]
Hi @vetss, 
Should I change my pull request, switching to Java 1.7?

Also I'm using jss7 CAP stack under Java 8 (without JBoss) and it's working fine.
Do you suggest downgrading to Java 7 anyway?

**Comment by vetss** [comment]
I have changed compile.source to 1.7. Thanks for this notification.
As far as you do not use JBoss you can use JAVA 8 (if you have no problems with this JAVA version).

I am closing this issue now.
