### ISSUE TITLE
It's unclear how to log all outgoing messages through CAP stack

### ISSUE THREAD

**Issue by raidan2** [RestComm/jss7#153]
Well, looking into **org.mobicents.protocols.ss7.cap.service.circuitSwitchedCall.CAPDialogCircuitSwitchedCallImpl**:

``` java
    @Override
    public Long addApplyChargingRequest(int customInvokeTimeout,
            CAMELAChBillingChargingCharacteristics aChBillingChargingCharacteristics, SendingSideID partyToCharge,
            CAPExtensions extensions, AChChargingAddress aChChargingAddress) throws CAPException {

        if (this.appCntx != CAPApplicationContext.CapV2_gsmSSF_to_gsmSCF
                && this.appCntx != CAPApplicationContext.CapV3_gsmSSF_scfGeneric
                && this.appCntx != CAPApplicationContext.CapV4_gsmSSF_scfGeneric
                && this.appCntx != CAPApplicationContext.CapV4_scf_gsmSSFGeneric)
            throw new CAPException(
                    "Bad application context name for addApplyChargingRequest: must be CapV2_gsmSSF_to_gsmSCF, CapV3_gsmSSF_scfGeneric, CapV4_gsmSSF_scfGeneric or CapV4_scf_gsmSSFGeneric");

        Invoke invoke = this.capProviderImpl.getTCAPProvider().getComponentPrimitiveFactory()
                .createTCInvokeRequest(InvokeClass.Class2);
        if (customInvokeTimeout == _Timer_Default)
            invoke.setTimeout(_Timer_CircuitSwitchedCallControl_Short);
        else
            invoke.setTimeout(customInvokeTimeout);

        OperationCode oc = this.capProviderImpl.getTCAPProvider().getComponentPrimitiveFactory().createOperationCode();
        oc.setLocalOperationCode((long) CAPOperationCode.applyCharging);
        invoke.setOperationCode(oc);

        ApplyChargingRequestImpl req = new ApplyChargingRequestImpl(aChBillingChargingCharacteristics, partyToCharge,
                extensions, aChChargingAddress);
        AsnOutputStream aos = new AsnOutputStream();
        req.encodeData(aos);

        Parameter p = this.capProviderImpl.getTCAPProvider().getComponentPrimitiveFactory().createParameter();
        p.setTagClass(req.getTagClass());
        p.setPrimitive(req.getIsPrimitive());
        p.setTag(req.getTag());
        p.setData(aos.toByteArray());
        invoke.setParameter(p);

        Long invokeId;
        try {
            invokeId = this.tcapDialog.getNewInvokeId();
            invoke.setInvokeId(invokeId);
        } catch (TCAPException e) {
            throw new CAPException(e.getMessage(), e);
        }

        this.sendInvokeComponent(invoke);

        return invokeId;
    }
```

How to log my outgoing ApplyChargingRequestImpl?
I don't see any extension point to do that.

Maybe we should allow to register listener of CAPServiceCircuitSwitchedCallListener in this class to intercept outgoing messages we interested in?

Same story for GPRS and SMS parts.

**Comment by vetss** [comment]
Hello @raidan2 

can you please explain more your needs / tasks and what is missing from your point of view

**Comment by raidan2** [comment]
@vetss 
Well, what I really want is some way to collect raw data (sending and receiving) for multiple purposes:

1. Audit (in case of any issue - just look into data I got and see what's wrong)
2. Building black-box test scenarios (have a way to represent CAP messages in some text form, XML then replay it, sending and expecting messages — acting as gsmSSF).


First option is already there, class AssociationImpl prints Rx/Tx messages into standard logger.
Unfortunately I'm not sure if it possible to intercept those Payloads to save it into my own storage (for future usage).


I see you have a lot of functional tests but I'm not sure I want to go this way.
I'd like to have a way to write message content in a text file, then replay it (send through local jss7 setup) and check expectation.
I found out I don't know how to collect message content I'm sending to gsmSSF (by calling #addApplyChargingRequest for instance). In other words, when I call method 
`dialog.addApplyChargingRequest(...);`
I'd like to see how this message looks like to expect it in tests.

**Comment by vetss** [comment]
org.mobicents.protocols.ss7.map.functional.MAPFunctionalTest has a possibility to write data traffic in some pcap file. You can activate it by adding of code line "saveTrafficInFile()" before primitive sending. Then you can just write code that will send requests / respnses and then you will be just able to open pcap file in WireShark and check content.

SS7 Simulator also can write traffic into pcap file.

If you want to have some HEX/binary data you will need to use code like unit tests or add your own code to some part that will store your data. 

If you have some other idea of logging feel free to suggest details of your solution.

**Comment by knosach** [comment]
closed due to inactivity
