### ISSUE TITLE
How to deploy jss7 and open using jboss ?

### ISSUE THREAD

**Issue by jeenareload** [RestComm/jss7#158]

**Comment by vetss** [comment]
Hello @jeenareload 

your question is big enouph. May I ask you firstly read manuals:
http://documentation.telestax.com/core/ss7/SS7_Stack_Installation_Guide.html
http://documentation.telestax.com/core/ss7/SS7_Stack_User_Guide.html

**Comment by jeenareload** [comment]
Hi @vetss 
Thanks for your response. I have successfully deploy it on JBOSS server,
