### ISSUE TITLE
RoutingLabelFormat does not support ANSI_Sls5Bit

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#16]
1) org.mobicents.protocols.ss7.mtp.RoutingLabelFormat has two different values:
ANSI_Sls8Bit
ANSI_Sls5Bit
But it support only one value in method:
public static RoutingLabelFormat getInstance(String format)
(only "ANSI" string value that corresponds to ANSI_Sls8Bit).
We need to accept "ANSI_Sls8Bit" and "ANSI_Sls5Bit" and also have a back support for "ANSI" value.
2) we need to find all places in mt3 and m3ua stackes and provide a proper code for both values processing.

**Comment by knosach** [comment]
closed by https://github.com/RestComm/jss7/commit/91be33cd42f03ba030d6e2381b91a96f76354269
