### ISSUE TITLE
Running SS7 simulator in real network

### ISSUE THREAD

**Issue by Mohamed-Ahmed-Abdullah** [RestComm/jss7#163]
Hi, 

when we run the SS7 in the same machine with the default configuration for both sides (A and B) every thing is working fine.
but when we move the server (B side) to different machine no connection happen.
in fact when the remote IP is anything but the loopback (127.0.0.1) no packages appear in wireshark 

Can you help please

**Comment by vetss** [comment]
You need to specify proper peer's IP addresses instead of 127.0.0.1 in both client and server sides

**Comment by Mohamed-Ahmed-Abdullah** [comment]
i opened new application and association in the STP 

in windows i get this error
java.lang.UnsupportedOperationException: SCTP not supported on this platform
it's normal because windows doesn't have support for SCTP 
So..
i installed Virtualbox with Ubuntu14.04
but i keep getting the next error when i am using the client
there is no firewall between me and the STP and there is association to my static IP 

165184 [AWT-EventQueue-0] INFO org.mobicents.protocols.ss7.tools.simulator.management.TesterHost  - TCAP+MAP has been started

16:47:59,733 INFO  [TesterHost] ATI Client has been started

165190 [AWT-EventQueue-0] INFO org.mobicents.protocols.ss7.tools.simulator.management.TesterHost  - ATI Client has been started

16:48:07,219 ERROR [AssociationImpl] Error while initiating a connection
java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.SctpChannelImpl.bind(SctpChannelImpl.java:187)
	at org.mobicents.protocols.sctp.AssociationImpl.doInitiateConnectionSctp(AssociationImpl.java:779)
	at org.mobicents.protocols.sctp.AssociationImpl.initiateConnection(AssociationImpl.java:745)
	at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:121)
	at java.lang.Thread.run(Thread.java:745)
172676 [Thread-1] ERROR org.mobicents.protocols.sctp.AssociationImpl  - Error while initiating a connection
java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.SctpChannelImpl.bind(SctpChannelImpl.java:187)
	at org.mobicents.protocols.sctp.AssociationImpl.doInitiateConnectionSctp(AssociationImpl.java:779)
	at org.mobicents.protocols.sctp.AssociationImpl.initiateConnection(AssociationImpl.java:745)
	at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:121)
	at java.lang.Thread.run(Thread.java:745)
16:48:17,259 ERROR [AssociationImpl] Error while initiating a connection
java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.SctpChannelImpl.bind(SctpChannelImpl.java:187)
	at org.mobicents.protocols.sctp.AssociationImpl.doInitiateConnectionSctp(AssociationImpl.java:779)
	at org.mobicents.protocols.sctp.AssociationImpl.initiateConnection(AssociationImpl.java:745)
	at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:121)
	at java.lang.Thread.run(Thread.java:745)


and when i tried to run it as a server i get the next error when i start the server 

Event:
M3ua Stopped (didn't start) 

Message:
Exception when starting M3uaMan - java.net.BindException: Cannot assign requested address

Stacktrace:
sun.nio.ch.Net.bind0(Native Method)
sun.nio.ch.Net.bind(Net.java:463)
sun.nio.ch.Net.bind(Net.java:455)
sun.nio.ch.SctpServerChannelImpl.bind(SctpServerChannelImpl.java:109)
com.sun.nio.sctp.SctpServerChannel.bind(SctpServerChannel.java:184)
org.mobicents.protocols.sctp.ServerImpl.doInitSocketSctp(ServerImpl.java:183)
org.mobicents.protocols.sctp.ServerImpl.initSocket(ServerImpl.java:157)
org.mobicents.protocols.sctp.ServerImpl.start(ServerImpl.java:112)
org.mobicents.protocols.sctp.ManagementImpl.startServer(ManagementImpl.java:647)
org.mobicents.protocols.ss7.tools.simulator.level1.M3uaMan.initM3ua(M3uaMan.java:682)
org.mobicents.protocols.ss7.tools.simulator.level1.M3uaMan.start(M3uaMan.java:549)
org.mobicents.protocols.ss7.tools.simulator.management.TesterHost.start(TesterHost.java:468)
org.mobicents.protocols.ss7.tools.simulatorgui.TestingForm$5.actionPerformed(TestingForm.java:256)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
java.awt.Component.processMouseEvent(Component.java:6516)
javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
java.awt.Component.processEvent(Component.java:6281)
java.awt.Container.processEvent(Container.java:2229)
java.awt.Component.dispatchEventImpl(Component.java:4872)
java.awt.Container.dispatchEventImpl(Container.java:2287)
java.awt.Component.dispatchEvent(Component.java:4698)
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
java.awt.Container.dispatchEventImpl(Container.java:2273)
java.awt.Window.dispatchEventImpl(Window.java:2719)
java.awt.Component.dispatchEvent(Component.java:4698)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
java.awt.EventQueue.access$300(EventQueue.java:103)
java.awt.EventQueue$3.run(EventQueue.java:706)
java.awt.EventQueue$3.run(EventQueue.java:704)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
java.awt.EventQueue$4.run(EventQueue.java:720)
java.awt.EventQueue$4.run(EventQueue.java:718)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

i am using the ports 2905 locally and 3326 in the server(STP) and they are not used  

am i missing something? 
Can you help please

**Comment by Mohamed-Ahmed-Abdullah** [comment]
I was facing silly problems with the network, i had to make sure the STP can ping my machine and vise versa also i had to make sure all the ports are open. 
i had another silly problem with windows, it doesn't have support for the SCTP protocol, so i had to use linux .
But now i am connected to the STP. The SCTP protocol is connected but when i send the ATI Message i didn't get a response. my configuration as follow:
*  I make sure to open a new application in the STP with my static ip and port number and use the proper OPC and DPC, and i make sure i am using the same routing context 
* The role setting is "client" and all the other settings using the default value 
* in layer 2 (SCCP) i am using rout on DPC and SSN, i have DPC configures in the STP but i know nothing about the SSN so i used the default: 8 (HLR) 

am i missing anything?? can you help please !!

**Comment by vetss** [comment]
Hello @Mohamed-Ahmed-Abdullah 

your case looks like some configuring issue. If you unable to solve it, try to ask community for help in the forum: https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/restcomm

I am closing this issue.
