### ISSUE TITLE
2.1.0.Final Binaries missing in repository

### ISSUE THREAD

**Issue by arslan70** [RestComm/jss7#166]
Hey, I was working on upgrading an old module to use 2.1.0.Final in a maven built project but the binaries at 
https://oss.sonatype.org/content/groups/public/org/mobicents/protocols/ss7/mobicents-ss7/
are not available for 2.1.0.FINAL so the build process fails.

Can the libraries for this version be made available?

-Arslan

**Comment by deruelle** [comment]
Unfortunately no, it was before the Continuous integration and delivery was in place. Can you upgrade to latest jSS7 instead ?
