### ISSUE TITLE
Double exchange Query

### ISSUE THREAD

**Issue by conallprendergast** [RestComm/jss7#170]
Hi,
Is it possible to set up the jss7 simulator GUI with double exchange with two routing contexts?
Like this: https://tools.ietf.org/html/rfc4666#section-5.6.2
Thanks in advance for your help

**Comment by vetss** [comment]
Hello @conallprendergast 

You can switch single exchange / doubde exchange by option: "M3UA Exchange type".
"DE" means "double exchange".

**Comment by conallprendergast** [comment]
Hi,
Thanks for the response. 
The problem I am having is that the following packet exchange occurs during the "routing context exchange" part of the handshake.

 
                 IPSP-A                                                        IPSP-B

                 |<------- ASP Active(RCb)--------------------|  RC: Routing Context
                 |-----ASP Active Ack (RCb)------------------>|      (optional)
                 |                                                                      |
                 **|------- ASP Active(RCb)-------------------->|  RC: Routing Context
                 |<-----ASP Active Ack (RCb)------------------|      (optional)**
                 |                                                                      |
                **|<------- ASP Active(RCa)--------------------|  RC: Routing Context
                 |-----ASP Active Ack (RCa)------------------>|      (optional)**
                 |------- ASP Active(RCa)--------------------->|  RC: Routing Context
                 |<-----ASP Active Ack (RCa)------------------|      (optional)
               

The sections in bold do not appear in the link above.
Thanks.
PS. Im fairly new to this so apologies if it is a simple question

**Comment by knosach** [comment]
hi @conallprendergast 

for double exchange, you need to set M3UA Exchange type to `DE` on M3UA client (jss7 simulator) and on M3UA server.

If you need customer support 24/7, you should request a professional support instead of waiting for community support.
You can request it from https://accounts.restcomm.com/registration.jsp

BR
