### ISSUE TITLE
Setting wrong EncodingScheme type in SCCP

### ISSUE THREAD

**Issue by Peramuthan** [RestComm/jss7#180]
Hi All,

In both the version of jSS7 7.1.1385 & 7.0.1383

File name: BCDEvenEncodingScheme.java

@Override
    public EncodingSchemeType getType() {
        return EncodingSchemeType.BCD_ODD;
    }

The above function return statement should be corrected as below
EncodingSchemeType.BCD_ODD to EncodingSchemeType.BCD_EVEN

Till now its not creating any issue on sccp layer.

Thanks & Regards,
Peramuthan R

**Comment by vetss** [comment]
Hello @Peramuthan 

this is a bug. Thanks for bug report. We need to fix it.

**Comment by vetss** [comment]
By the way @Peramuthan , do not you want to contribute it ? You may add PullRequest with a bug fix into https://github.com/RestComm/jss7/pulls.

**Comment by Peramuthan** [comment]
Yes Vetss, i want contribute it? Let me know the complete procedure to do

Thanks & Regards,
Peramuthan Rameshkumar

**Comment by vetss** [comment]
Hello @Peramuthan 

Please read THE TELESTAX OPEN SOURCE PLAYBOOK:
https://telestax.com/open-source/#Contribute
and sign Contributor License Agreement

Then if you can contribute you need to download the lastes binaries, implement some patch and create a pull request in https://github.com/RestComm/jss7/pulls

**Comment by vetss** [comment]
Fixed non-netty version as:
https://github.com/RestComm/jss7/commit/65e05766acfad2eca887312df70eed1cb8f506de

**Comment by vetss** [comment]
Hello @Peramuthan

I have added you code into non-netty branch. Thanks for your work.
Can you please prepare the same update for master branch ?

**Comment by Peramuthan** [comment]
Hi,

Yes merged in master branch also

Thanks & Regards,
Peramuthan

**Comment by vetss** [comment]
Hello @Peramuthan 

> Yes merged in master branch also

I found only pull request for a non-netty branch and not for master branch...
https://github.com/RestComm/jss7/commit/65e05766acfad2eca887312df70eed1cb8f506de

Let's add new staff for master branch. We are adding into non-netty branch only updates with critical bugs. Mainstreem is master branch now.

**Comment by Peramuthan** [comment]
Hello @vetss 

Under below pull request only submitted this fix into master
24052be
https://github.com/Peramuthan/ss7bugfix/commit/24052be3f7530db7904df8ecba64c283081cd7c2

**Comment by vetss** [comment]
Hello @Peramuthan 

That is some link to your fork of the repo. I can not see it there: https://github.com/RestComm/jss7/commits/master

I meant a pull request in https://github.com/RestComm/jss7/pulls part. I found there only PR for non-netty branch.

**Comment by Peramuthan** [comment]
Hello @vetss 

while creating the PullRequest  under this  https://github.com/RestComm/jss7/pulls for this issue changes. not able to see my private branch(peramuthan_patch1).
So now i created pull request in mentioned path but seeing some more commits also in PR.
Please tell me the exact the procedure how to do this?

Thanks & Regards,
Peramuthan R

**Comment by vetss** [comment]
Hello @Peramuthan 

I see your pull requests contains a lot of updates that are not needed.
I you want to create a pull request depending on master baranch, then you need:
- make a copy of master branch in your repo fork
- apply there needed changes (manully if they are simple) or you can for example make "cherry-pick" procedures
- commit all this
- create a PR

Have I answered on your question ?

**Comment by vetss** [comment]
Fixed mster branch by commit:
https://github.com/RestComm/jss7/commit/fb573a536d7a77d330f412cf321903eba42d56ca

Thanks @Peramuthan for your updates. I am closing the issue.
