### ISSUE TITLE
Support for  MAP Load test

### ISSUE THREAD

**Issue by Hariniravi8** [RestComm/jss7#183]
Would like to know if JSS7 simulator can be used for load test. Pls share the details.

**Comment by vetss** [comment]
Hello @Hariniravi8 

SS7 Simulator is a GUI application and it is more for functional tests not for load tests (GUI itslef consumes some resources). But you can try to do it nevertheless.
One tip is: turn on the option "One notification for 100 dialogs" in tests that allow it (to reduce of message count that are put into GUI).

**Comment by Hariniravi8** [comment]
Thanks Vetss
