### ISSUE TITLE
broken links at wiki/USSDTestingwithDialogicBoards

### ISSUE THREAD

**Issue by nicosmaris** [RestComm/jss7#188]
The link 'map-demo' is broken, can you provide the right one?

The first two links can be updated with the following ones, right?

https://www.dialogic.com/~/media/manuals/ss7/cd/ProductSpecific/SPCI-CPM8/ProgrammersManual/SPCI-PM.pdf

http://resource.dialogic.com/telecom/support/ss7/cd/GenericInfo/GeneralDocumentation/U30SSS03-MTU-MTR-UG.pdf

**Comment by deruelle** [comment]
@nicosmarris do you want to do a Pull request with fixing the docs that are located in https://github.com/RestComm/jss7/tree/master/docs/userguide/sources-asciidoc. Wiki may not be ideal place for this.

**Comment by nicosmaris** [comment]
Sure, we can continue the discussion at https://github.com/RestComm/jss7/pull/189

**Comment by vetss** [comment]
Hello @nicosmaris 

I have committed your PR https://github.com/RestComm/jss7/pull/189
Thanks for your work.
