### ISSUE TITLE
CLI for JBOSS 10 (WildFly)

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#211]
WildFly has it own CLI interface. We need to check if we can reuse it for JSS7 stack instead of usage of native JSS7 project CLI solution.

If it is very difficult - let's separate CLI from JSS7 and SMPP Extension projects into a separate WildFly Extension to be reusable by several projects.

**Comment by knosach** [comment]
fixed by https://github.com/RestComm/jss7/commit/e51f03300d2ba7e207040cfab13935320ad33c8c

**Comment by vetss** [comment]
The current state - we still need to investigate of a possibility of usage of wildfly CLI. Usage of a server CLI is preferable becuase it is more stable and securable as compared with our implementation. We may not make a separate implementation of CLI (we have it already in jss7 lib) we can make only an intermediate module as a bridge between a wildfly server and surrent CLI implementation.

We need to understand that we can/can not use of wildfly CLI because of some reason make this update (for example no simple way of usage of jss7 implemenation). We need to provide getting of command, sending it to an existing jss7 CLI and writing back a result + command helpers with command completers by TAB. Old CLI implementation has a CLI helpers as files on board and commands / parameters tree, possibly we can put them into .

We may think of postponing of the task because it is not critical.
