### ISSUE TITLE
jSS7 Simulator: add ability to configure some CAP messages parameters

### ISSUE THREAD

**Issue by mnowa** [RestComm/jss7#213]
Extend  jSS7 Simulator with support for configure few basic CAMEL messages parameters. Especially add possibility to specify 

- **InitialDP** params like: CallingPartyNumber, CalledPartyBCDNumber, CalledPartyNumber, ServiceKey or EventTypeBCSM, 
- **Connect** parameter (DestinationRoutingAddress)
- **Release** parmater (Cuase)

**Comment by vetss** [comment]
Hello @mnowa 

thanks for opening an issue. Will you be able to contribute this issue ?

**Comment by mnowa** [comment]
Hello @vetss 
I will contribute. I opened the issue and I wanted to assign myself to it however I wasn't able to do it... Please assign it to me. I will provide the implementation soon

**Comment by vetss** [comment]
Thanks @mnowa for you update. I have added https://github.com/RestComm/jss7/pull/216 with my little update.

Fixed by:
https://github.com/RestComm/jss7/commit/6af580192006ac642cf3488afc6b8a9f7a1d6f1c
https://github.com/RestComm/jss7/commit/4d4dc25eb9bf78a19ad09e877c214f05e304a9ca
