### ISSUE TITLE
jss7-management-console issue 

### ISSUE THREAD

**Issue by Nabilfaidi** [RestComm/jss7#214]
I would like to ask for help, i have installed the Resctomm SS7Stack. I can open the GUI but i can't add a Sctp server ,Sccp rule even i can't sign out.I tried using a sheel command and it's working. My OS is Ubuntu 16.04. Thanks in advance

**Comment by wrongt** [comment]
do you have jolokia.war deployed on you're app server?

**Comment by Nabilfaidi** [comment]
thanks wrongt 
this what i got in http://localhost:8080/jolokia/
 {"request":{"type":"version"},"value":{"agent":"1.1.0","protocol":"7.0","info":{"product":"jboss","vendor":"RedHat","version":"5.0.0.CR2"}},"timestamp":1488817759,"status":200}
normally it's deployed

**Comment by wrongt** [comment]
@Nabilfaidi please check if you have  SCTPManagement mbean declared, this url:   
> http://127.0.0.1:8080/jolokia/search/org.mobicents.ss7:layer=SCTP,type=Management,name=*

should looking for it

**Comment by Nabilfaidi** [comment]
this is the response of the url http://127.0.0.1:8080/jolokia/search/org.mobicents.ss7:layer=SCTP,type=Management,name=*

{"request":{"mbean":"org.mobicents.ss7:layer=SCTP,name=*,type=Management","type":"search"},"value":[],"timestamp":1488876420,"status":200}

**Comment by wrongt** [comment]
seems you don't have configured jss7 stack
what is your app server, jboss 5 or wildfly 10 ?
the response of the above url should be:
`$ curl -s "http://127.0.0.1:8080/jolokia/search/org.mobicents.ss7:layer=SCTP,type=Management,name=*"
{"request":{"mbean":"org.mobicents.ss7:layer=SCTP,name=*,type=Management","type":"search"},"value":["org.mobicents.ss7:layer=SCTP,name=SCTPManagement,type=Management"],"timestamp":1488899505,"status":200}`

**Comment by Nabilfaidi** [comment]
jboss 5
 for jss7 stack i just did 
/Downloads/restcomm-jss7-7.1.1385/ss7$ ant deploy
Buildfile: /home/nabil/Downloads/restcomm-jss7-7.1.1385/ss7/build.xml

deploy:
     [copy] Copying 46 files to /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy/restcomm-ss7-service
     [copy] Copying 2 files to /home/nabil/Downloads/jboss-5.0.0.CR2/bin
     [copy] Copying 10 files to /home/nabil/Downloads/jboss-5.0.0.CR2/lib
     [copy] Copying 2 files to /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy

BUILD SUCCESSFUL
Total time: 0 seconds

**Comment by wrongt** [comment]
now in your app in META-INF you can declare jboss-beans.xml with the next context: 
[jboss-beans.xml.zip](https://github.com/RestComm/jss7/files/824919/jboss-beans.xml.zip)

or you can proceed with installation of ss7simulator, smsc or ussdgateway

**Comment by Nabilfaidi** [comment]
the application is deployed, but still the same issue 
please see below:
/Downloads/jboss-5.0.0.CR2/bin$ sh run.sh 
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /home/nabil/Downloads/jboss-5.0.0.CR2/

  JAVA: java

  JAVA_OPTS: -Dprogram.name=run.sh -Xms128m -Xmx512m -XX:MaxPermSize=256m -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djava.net.preferIPv4Stack=true

  CLASSPATH: /home/nabil/Downloads/jboss-5.0.0.CR2//bin/run.jar

=========================================================================

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
17:43:51,470 INFO  [ServerImpl] Starting JBoss (Microcontainer)...
17:43:51,470 INFO  [ServerImpl] Release ID: JBoss [Morpheus] 5.0.0.CR2 (build: SVNTag=JBoss_5_0_0_CR2 date=200809171139)
17:43:51,471 INFO  [ServerImpl] Home Dir: /home/nabil/Downloads/jboss-5.0.0.CR2
17:43:51,472 INFO  [ServerImpl] Home URL: file:/home/nabil/Downloads/jboss-5.0.0.CR2/
17:43:51,472 INFO  [ServerImpl] Library URL: file:/home/nabil/Downloads/jboss-5.0.0.CR2/lib/
17:43:51,472 INFO  [ServerImpl] Patch URL: null
17:43:51,472 INFO  [ServerImpl] Server Name: default
17:43:51,472 INFO  [ServerImpl] Server Home Dir: /home/nabil/Downloads/jboss-5.0.0.CR2/server/default
17:43:51,472 INFO  [ServerImpl] Server Home URL: file:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/
17:43:51,472 INFO  [ServerImpl] Server Data Dir: /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data
17:43:51,472 INFO  [ServerImpl] Server Temp Dir: /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/tmp
17:43:51,472 INFO  [ServerImpl] Server Config URL: file:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/conf/
17:43:51,473 INFO  [ServerImpl] Server Library URL: file:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/lib/
17:43:51,473 INFO  [ServerImpl] Root Deployment Filename: jboss-service.xml
17:43:51,748 INFO  [ServerImpl] Starting Microcontainer, bootstrapURL=file:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/conf/bootstrap.xml
17:43:52,093 INFO  [CopyMechanism] VFS temp dir: /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/tmp
17:43:52,094 INFO  [ZipEntryContext] VFS force nested jars copy-mode is enabled.
17:43:52,726 INFO  [ServerInfo] Java version: 1.8.0_03-Ubuntu,Oracle Corporation
17:43:52,727 INFO  [ServerInfo] Java VM: OpenJDK 64-Bit Server VM 25.03-b03,Oracle Corporation
17:43:52,727 INFO  [ServerInfo] OS-System: Linux 4.4.0-21-generic,amd64
17:43:52,749 INFO  [JMXKernel] Legacy JMX core initialized
17:43:53,394 INFO  [MetaDataAwareProfile] Using profile root:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default
17:43:54,086 INFO  [WebService] Using RMI server codebase: http://127.0.0.1:8083/
17:43:57,306 WARN  [HackClassloaderMetaDataDeployer] FIXME Using loader repository config: jboss.console:sar=console-mgr.sar for  vfsfile:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy/management/console-mgr.sar/ use classloading metadata not loader repository config
17:43:57,490 INFO  [AspectDeployer] Deploying xml into org.jboss.aop.AspectManager@2e889607 for BaseClassLoader@6af8d492{vfsfile:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy/ejb3-interceptors-aop.xml}
17:44:02,205 INFO  [JMXConnectorServerService] JMX Connector server: service:jmx:rmi://127.0.0.1/jndi/rmi://127.0.0.1:1090/jmxconnector
17:44:02,240 INFO  [MailService] Mail Service bound to java:/Mail
17:44:02,421 INFO  [NativeServerConfig] JBoss Web Services - Stack Native Core
17:44:02,421 INFO  [NativeServerConfig] 3.0.3.GA
17:44:02,712 WARN  [JBossASSecurityMetadataStore] WARNING! POTENTIAL SECURITY RISK. It has been detected that the MessageSucker component which sucks messages from one node to another has not had its password changed from the installation default. Please see the JBoss Messaging user guide for instructions on how to do this.
17:44:02,809 INFO  [TransactionManagerService] JBossTS Transaction Service (JTA version) - JBoss Inc.
17:44:02,809 INFO  [TransactionManagerService] Setting up property manager MBean and JMX layer
17:44:02,931 INFO  [TransactionManagerService] Initializing recovery manager
17:44:02,982 INFO  [TransactionManagerService] Recovery manager configured
17:44:02,982 INFO  [TransactionManagerService] Binding TransactionManager JNDI Reference
17:44:02,991 INFO  [TransactionManagerService] Starting transaction recovery manager
17:44:03,190 INFO  [AprLifecycleListener] The Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
17:44:03,226 INFO  [Http11Protocol] Initializing Coyote HTTP/1.1 on http-127.0.0.1-8080
17:44:03,226 INFO  [AjpProtocol] Initializing Coyote AJP/1.3 on ajp-127.0.0.1-8009
17:44:03,226 INFO  [Catalina] Initialization processed in 129 ms
17:44:03,227 INFO  [StandardService] Starting service jboss.web
17:44:03,228 INFO  [StandardEngine] Starting Servlet Engine: JBoss Web/2.1.1.CR7
17:44:03,255 INFO  [Catalina] Server startup in 28 ms
17:44:03,282 INFO  [TomcatDeployment] deploy, ctxPath=/jbossws, vfsUrl=jbossws.sar/jbossws-management.war
17:44:03,557 INFO  [TomcatDeployment] deploy, ctxPath=/invoker, vfsUrl=http-invoker.sar/invoker.war
17:44:03,585 INFO  [TomcatDeployment] deploy, ctxPath=/web-console, vfsUrl=management/console-mgr.sar/web-console.war
17:44:03,761 INFO  [RARDeployment] Required license terms exist, view vfszip:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy/jboss-local-jdbc.rar/META-INF/ra.xml
17:44:03,767 INFO  [RARDeployment] Required license terms exist, view vfszip:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy/jboss-xa-jdbc.rar/META-INF/ra.xml
17:44:03,773 INFO  [RARDeployment] Required license terms exist, view vfszip:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy/jms-ra.rar/META-INF/ra.xml
17:44:03,777 INFO  [RARDeployment] Required license terms exist, view vfszip:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy/mail-ra.rar/META-INF/ra.xml
17:44:03,784 INFO  [RARDeployment] Required license terms exist, view vfszip:/home/nabil/Downloads/jboss-5.0.0.CR2/server/default/deploy/quartz-ra.rar/META-INF/ra.xml
17:44:03,821 INFO  [SimpleThreadPool] Job execution threads will use class loader of thread: main
17:44:03,837 INFO  [QuartzScheduler] Quartz Scheduler v.1.5.2 created.
17:44:03,838 INFO  [RAMJobStore] RAMJobStore initialized.
17:44:03,838 INFO  [StdSchedulerFactory] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
17:44:03,838 INFO  [StdSchedulerFactory] Quartz scheduler version: 1.5.2
17:44:03,839 INFO  [QuartzScheduler] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
17:44:04,089 INFO  [ConnectionFactoryBindingService] Bound ConnectionManager 'jboss.jca:service=DataSourceBinding,name=DefaultDS' to JNDI name 'java:DefaultDS'
17:44:04,217 WARN  [QuartzTimerServiceFactory] sql failed: CREATE TABLE QRTZ_JOB_DETAILS(JOB_NAME VARCHAR(80) NOT NULL, JOB_GROUP VARCHAR(80) NOT NULL, DESCRIPTION VARCHAR(120) NULL, JOB_CLASS_NAME VARCHAR(128) NOT NULL, IS_DURABLE VARCHAR(1) NOT NULL, IS_VOLATILE VARCHAR(1) NOT NULL, IS_STATEFUL VARCHAR(1) NOT NULL, REQUESTS_RECOVERY VARCHAR(1) NOT NULL, JOB_DATA BINARY NULL, PRIMARY KEY (JOB_NAME,JOB_GROUP))
17:44:04,246 INFO  [SimpleThreadPool] Job execution threads will use class loader of thread: main
17:44:04,252 INFO  [QuartzScheduler] Quartz Scheduler v.1.5.2 created.
17:44:04,252 INFO  [JobStoreCMT] Using db table-based data access locking (synchronization).
17:44:04,270 INFO  [JobStoreCMT] Removed 0 Volatile Trigger(s).
17:44:04,270 INFO  [JobStoreCMT] Removed 0 Volatile Job(s).
17:44:04,270 INFO  [JobStoreCMT] JobStoreCMT initialized.
17:44:04,270 INFO  [StdSchedulerFactory] Quartz scheduler 'JBossEJB3QuartzScheduler' initialized from an externally provided properties instance.
17:44:04,270 INFO  [StdSchedulerFactory] Quartz scheduler version: 1.5.2
17:44:04,273 INFO  [JobStoreCMT] Freed 0 triggers from 'acquired' / 'blocked' state.
17:44:04,275 INFO  [JobStoreCMT] Recovering 0 jobs that were in-progress at the time of the last shut-down.
17:44:04,275 INFO  [JobStoreCMT] Recovery complete.
17:44:04,275 INFO  [JobStoreCMT] Removed 0 'complete' triggers.
17:44:04,275 INFO  [JobStoreCMT] Removed 0 stale fired job entries.
17:44:04,278 INFO  [QuartzScheduler] Scheduler JBossEJB3QuartzScheduler_$_NON_CLUSTERED started.
17:44:04,403 INFO  [ServerPeer] JBoss Messaging 1.4.1.CR1 server [0] started
17:44:04,442 INFO  [QueueService] Queue[/queue/ExpiryQueue] started, fullSize=200000, pageSize=2000, downCacheSize=2000
17:44:04,446 WARN  [ConnectionFactoryJNDIMapper] supportsFailover attribute is true on connection factory: jboss.messaging.connectionfactory:service=ClusteredConnectionFactory but post office is non clustered. So connection factory will *not* support failover
17:44:04,446 WARN  [ConnectionFactoryJNDIMapper] supportsLoadBalancing attribute is true on connection factory: jboss.messaging.connectionfactory:service=ClusteredConnectionFactory but post office is non clustered. So connection factory will *not* support load balancing
17:44:04,479 INFO  [ConnectionFactory] Connector bisocket://127.0.0.1:4457 has leasing enabled, lease period 10000 milliseconds
17:44:04,479 INFO  [ConnectionFactory] org.jboss.jms.server.connectionfactory.ConnectionFactory@2743bce6 started
17:44:04,481 INFO  [QueueService] Queue[/queue/DLQ] started, fullSize=200000, pageSize=2000, downCacheSize=2000
17:44:04,483 INFO  [ConnectionFactory] Connector bisocket://127.0.0.1:4457 has leasing enabled, lease period 10000 milliseconds
17:44:04,483 INFO  [ConnectionFactory] org.jboss.jms.server.connectionfactory.ConnectionFactory@1eb638b0 started
17:44:04,483 INFO  [ConnectionFactory] Connector bisocket://127.0.0.1:4457 has leasing enabled, lease period 10000 milliseconds
17:44:04,483 INFO  [ConnectionFactory] org.jboss.jms.server.connectionfactory.ConnectionFactory@6135fe73 started
17:44:04,528 INFO  [ConnectionFactoryBindingService] Bound ConnectionManager 'jboss.jca:service=ConnectionFactoryBinding,name=JmsXA' to JNDI name 'java:JmsXA'
17:44:04,532 INFO  [TomcatDeployment] deploy, ctxPath=/, vfsUrl=ROOT.war
17:44:04,559 INFO  [TomcatDeployment] deploy, ctxPath=/jmx-console, vfsUrl=jmx-console.war
17:44:04,590 INFO  [TomcatDeployment] deploy, ctxPath=/jolokia, vfsUrl=jolokia.war
17:44:04,610 INFO  [[/jolokia]] jolokia-agent: No access restrictor found at classpath:/jolokia-access.xml, access to all MBeans is allowed
17:44:04,734 INFO  [TomcatDeployment] deploy, ctxPath=/jss7-management-console, vfsUrl=jss7-management-console.war
17:44:05,089 INFO  [ManagementImpl] SCTP configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/SCTPManagement_sctp.xml
17:44:05,114 INFO  [ServerImpl] SctpServerChannel bound to=[/192.168.1.110:8011] 
17:44:05,115 INFO  [ServerImpl] Started Server=main
17:44:05,120 INFO  [SelectorThread] SelectorThread for Management=SCTPManagement started.
17:44:05,120 INFO  [ManagementImpl] Started SCTP Management=SCTPManagement WorkerThreads=0 SingleThread=true
17:44:05,189 INFO  [M3UAManagementImpl] M3UA configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/Mtp3UserPart_m3ua1.xml
17:44:05,227 INFO  [AssociationImpl] Started Association=Association [name=ussdgw, associationType=SERVER, ipChannelType=SCTP, hostAddress=, hostPort=0, peerAddress=192.168.1.111, peerPort=8012, serverName=main, extraHostAddress=[]]
17:44:05,228 INFO  [AssociationImpl] Started Association=Association [name=simulator, associationType=SERVER, ipChannelType=SCTP, hostAddress=, hostPort=0, peerAddress=192.168.1.110, peerPort=8013, serverName=main, extraHostAddress=[]]
17:44:05,229 INFO  [M3UAManagementImpl] Started M3UAManagement
17:44:05,247 INFO  [Scheduler] Starting 
17:44:05,247 INFO  [Scheduler] Started 
17:44:05,272 INFO  [SccpStackImpl-SccpStack] Starting ...
17:44:05,272 INFO  [SccpStackImpl-SccpStack] SCCP Management configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/SccpStack_management2.xml
17:44:05,286 INFO  [RouterImpl] SCCP Router configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/SccpStack_sccprouter2.xml
17:44:05,297 INFO  [RouterImpl] Started SCCP Router
17:44:05,300 INFO  [SccpResourceImpl] SCCP Resource configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/SccpStack_sccpresource2.xml
17:44:05,304 INFO  [SccpResourceImpl] Started Sccp Resource
17:44:05,304 INFO  [SccpStackImpl-SccpStack] Starting routing engine...
17:44:05,304 INFO  [SccpStackImpl-SccpStack] Starting management ...
17:44:05,304 INFO  [SccpStackImpl-SccpStack] Starting MSU handler...
17:44:05,334 INFO  [TCAPStackImpl-TcapStackMap] Starting ...org.mobicents.protocols.ss7.tcap.TCAPProviderImpl@42c2c490
17:44:05,334 INFO  [TCAPStackImpl-TcapStackMap] TCAP Management configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/TcapStackMap_management.xml
17:44:05,335 INFO  [TCAPProviderImpl] Starting TCAP Provider
17:44:05,335 WARN  [SccpManagement-SccpStack] Failed sendManagementMessage : Mtp3ServiceAccessPoint has not found for dpc=3
17:44:05,335 WARN  [SccpManagement-SccpStack] Failed sendManagementMessage : Mtp3ServiceAccessPoint has not found for dpc=2
17:44:05,335 INFO  [TCAPProviderImpl] Registered SCCP listener with address 8
17:44:05,340 INFO  [TCAPStackImpl-TcapStackCap] Starting ...org.mobicents.protocols.ss7.tcap.TCAPProviderImpl@41e7b38e
17:44:05,340 INFO  [TCAPStackImpl-TcapStackCap] TCAP Management configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/TcapStackCap_management.xml
17:44:05,340 INFO  [TCAPProviderImpl] Starting TCAP Provider
17:44:05,340 WARN  [SccpManagement-SccpStack] Failed sendManagementMessage : Mtp3ServiceAccessPoint has not found for dpc=3
17:44:05,340 WARN  [SccpManagement-SccpStack] Failed sendManagementMessage : Mtp3ServiceAccessPoint has not found for dpc=2
17:44:05,340 INFO  [TCAPProviderImpl] Registered SCCP listener with address 146
17:44:05,346 INFO  [TCAPStackImpl-TcapStack] Starting ...org.mobicents.protocols.ss7.tcap.TCAPProviderImpl@36c26700
17:44:05,346 INFO  [TCAPStackImpl-TcapStack] TCAP Management configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/TcapStack_management.xml
17:44:05,346 INFO  [TCAPProviderImpl] Starting TCAP Provider
17:44:05,347 WARN  [SccpManagement-SccpStack] Failed sendManagementMessage : Mtp3ServiceAccessPoint has not found for dpc=3
17:44:05,347 WARN  [SccpManagement-SccpStack] Failed sendManagementMessage : Mtp3ServiceAccessPoint has not found for dpc=2
17:44:05,347 INFO  [TCAPProviderImpl] Registered SCCP listener with address 9
17:44:05,400 INFO  [ShellServer] Starting SS7 management shell environment
17:44:05,402 INFO  [ShellServer] ShellExecutor listening at /127.0.0.1:3435
17:44:05,692 INFO  [SS7Service]  [[[[[[[[[ restcomm-ss7 7.1.1385 TCAP service started ]]]]]]]]] 
17:44:06,157 INFO  [SS7Service]  [[[[[[[[[ restcomm-ss7 7.1.1385 MAP service started ]]]]]]]]] 
17:44:06,179 INFO  [SS7Service]  [[[[[[[[[ restcomm-ss7 7.1.1385 CAP service started ]]]]]]]]] 
17:44:06,199 INFO  [SS7Service]  [[[[[[[[[ restcomm-ss7 7.1.1385 ISUP service started ]]]]]]]]] 
17:44:06,214 INFO  [Ss7Management] Starting ...
17:44:06,215 INFO  [MBeanHostImpl] Found MBeanServer matching for agentId=jboss
17:44:06,215 WARN  [MBeanHostImpl] Found non-matching MBeanServer with default domian = null
17:44:06,215 INFO  [Ss7Management] Started ...
17:44:06,223 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=ALARM,type=Management,name=AlarmHost
17:44:06,223 INFO  [Ss7Management] Registered MBean: AlarmHost
17:44:06,235 INFO  [CounterProviderManagement-CounterHost] Starting ...
17:44:06,235 INFO  [CounterProviderManagement-CounterHost] CounterManagement configuration file path /home/nabil/Downloads/jboss-5.0.0.CR2/server/default/data/CounterHost_CounterProvider.xml
17:44:06,239 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=COUNTER,type=Management,name=CounterHost
17:44:06,241 INFO  [Ss7Management] Registered MBean: CounterHost
17:44:06,242 INFO  [CounterProviderManagement-CounterHost] Started ...
17:44:06,255 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=SCTP,type=Management,name=SCTPManagement
17:44:06,256 INFO  [Ss7Management] Registered MBean: SCTPManagement
17:44:06,260 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=SCTP,type=Server,name=main
17:44:06,260 INFO  [Ss7Management] Registered MBean: main
17:44:06,264 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=SCTP,type=Association,name=ussdgw
17:44:06,264 INFO  [Ss7Management] Registered MBean: ussdgw
17:44:06,264 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=SCTP,type=Association,name=simulator
17:44:06,264 INFO  [Ss7Management] Registered MBean: simulator
17:44:06,288 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=Management,name=Mtp3UserPart
17:44:06,288 INFO  [Ss7Management] Registered MBean: Mtp3UserPart
17:44:06,289 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=AspFactory,name=asp1
17:44:06,289 INFO  [Ss7Management] Registered MBean: asp1
17:44:06,290 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=AspFactory,name=asp2
17:44:06,290 INFO  [Ss7Management] Registered MBean: asp2
17:44:06,290 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=AspFactory,name=AS2
17:44:06,290 INFO  [Ss7Management] Registered MBean: AS2
17:44:06,292 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=As,name=AS1
17:44:06,292 INFO  [Ss7Management] Registered MBean: AS1
17:44:06,295 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=Asp,name=asp1
17:44:06,295 INFO  [Ss7Management] Registered MBean: asp1
17:44:06,295 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=As,name=AS2
17:44:06,295 INFO  [Ss7Management] Registered MBean: AS2
17:44:06,296 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=Asp,name=asp2
17:44:06,296 INFO  [Ss7Management] Registered MBean: asp2
17:44:06,296 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=M3UA,type=Asp,name=AS2
17:44:06,296 INFO  [Ss7Management] Registered MBean: AS2
17:44:06,306 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=SCCP,type=Management,name=SccpStack
17:44:06,306 INFO  [Ss7Management] Registered MBean: SccpStack
17:44:06,312 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=SCCP,type=Router,name=SccpStack
17:44:06,312 INFO  [Ss7Management] Registered MBean: SccpStack
17:44:06,314 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=SCCP,type=Resource,name=SccpStack
17:44:06,314 INFO  [Ss7Management] Registered MBean: SccpStack
17:44:06,326 INFO  [TcapManagementJmx-TcapStack] Starting ...
17:44:06,330 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=TCAP,type=Management,name=TcapStack
17:44:06,332 INFO  [CounterProviderManagement-CounterHost] Registered CounterMediator: Tcap-TcapStack
17:44:06,332 INFO  [Ss7Management] Registered MBean: TcapStack
17:44:06,332 INFO  [TcapManagementJmx-TcapStack] Started ...
17:44:06,336 INFO  [TcapManagementJmx-TcapStackMap] Starting ...
17:44:06,337 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=TCAP,type=Management,name=TcapStackMap
17:44:06,337 INFO  [CounterProviderManagement-CounterHost] Registered CounterMediator: Tcap-TcapStackMap
17:44:06,337 INFO  [Ss7Management] Registered MBean: TcapStackMap
17:44:06,337 INFO  [TcapManagementJmx-TcapStackMap] Started ...
17:44:06,341 INFO  [TcapManagementJmx-TcapStackCap] Starting ...
17:44:06,342 INFO  [MBeanHostImpl] Registered MBean with ObjectName=org.mobicents.ss7:layer=TCAP,type=Management,name=TcapStackCap
17:44:06,342 INFO  [CounterProviderManagement-CounterHost] Registered CounterMediator: Tcap-TcapStackCap
17:44:06,342 INFO  [Ss7Management] Registered MBean: TcapStackCap
17:44:06,342 INFO  [TcapManagementJmx-TcapStackCap] Started ...
17:44:06,361 ERROR [ProfileServiceBootstrap] Failed to load profile: Summary of incomplete deployments (SEE PREVIOUS ERRORS FOR DETAILS):

*** CONTEXTS MISSING DEPENDENCIES: Name -> Dependency{Required State:Actual State}

RestcommLinksetManagement
 -> LinksetManager{Instantiated:** NOT FOUND Depends on 'LinksetManager' **}


*** CONTEXTS IN ERROR: Name -> Error

LinksetManager -> ** NOT FOUND Depends on 'LinksetManager' **


17:44:06,368 INFO  [Http11Protocol] Starting Coyote HTTP/1.1 on http-127.0.0.1-8080
17:44:06,379 INFO  [AjpProtocol] Starting Coyote AJP/1.3 on ajp-127.0.0.1-8009
17:44:06,382 INFO  [ServerImpl] JBoss (Microcontainer) [5.0.0.CR2 (build: SVNTag=JBoss_5_0_0_CR2 date=200809171139)] Started in 14s:908ms

**Comment by wrongt** [comment]
so, i guess, the issue is when after you fill with proper value "Create Server" form and press "Create" button the sctp server is not created and the form is not hidden. 
If i'm right, then please locate the sctp-oam-*.jar and m3ua-oam-*.jar and replace it with the attached jars
[m3ua-oam-8.0.0-SNAPSHOT.jar.zip](https://github.com/RestComm/jss7/files/825210/m3ua-oam-8.0.0-SNAPSHOT.jar.zip)
[sctp-oam-8.0.0-SNAPSHOT.jar.zip](https://github.com/RestComm/jss7/files/825213/sctp-oam-8.0.0-SNAPSHOT.jar.zip)
and try again.

**Comment by vetss** [comment]
Hello @Nabilfaidi 

I can see in logs LinksetManager and M3UA. Do you really need both ?
LinksetManager is used only for Dahdi SS7 cards.

**Comment by Nabilfaidi** [comment]
Hello @vetss 
thanks , sorry for the delay, i will only use m3ua.
The issue is only with web interface, i can't perform those actions: create sctp server, display sctp server created using the shell command, create m3ua as and asp, signout, but i can see alarms.
Please note that i' m using the default user admin.
Thanks in advance .

**Comment by vetss** [comment]
Hello @Nabilfaidi , @wrongt 

thanks @wrongt , I have added your update for this topic from https://github.com/RestComm/jss7/pull/217 that will fix this issue. Thank you for your update.

The update is added into master and non-netty branches.
This update will be available for work with WilfFly server when we merge jain-slee-3.x brances into master / non-netty branches.

This is a fix:
https://github.com/RestComm/jss7/commit/b2439b26a28b319c7b524eb653a82df3ab767492
