### ISSUE TITLE
M3UA handling of Two ASPs in an Application Server

### ISSUE THREAD

**Issue by abhayani** [RestComm/jss7#219]
M3UA as of today doesn't correctly handles "Two ASPs in an Application Server" as mentioned in section 5.1.3 of https://tools.ietf.org/html/rfc4666#section-5.1.3

If jSS7 is acting as AS side and has 2 ASP's in an AS (ASP can be in different VM too), and if first ASP is ACTIVE making AS ACTIVE, when next ASP sends ASPUP, it will receive ASPUP_ACK and at same time SWG will also send NTFY indicating that AS is ACTIVE. jSS7 should handle this and make AS ACTIVE. Instead it thinks NTFY (ACTIVE) is wrong message and sends ASP_ACTIVE to peer expecting the ASP_ACTIVE_ACK and again waits for NTFY (AS ACTIVE) which will never come and hence AS state doesn't change.

**Comment by jaimecasero** [comment]
@abhayani  can we try to spot the main parts that require change here:
Do we need to update the FSM here 
https://github.com/RestComm/jss7/blob/master/m3ua/impl/src/main/java/org/mobicents/protocols/ss7/m3ua/impl/AspImpl.java#L131 
??

**Comment by jaimecasero** [comment]
@abhayani  what about failover?
should we comply with sections as well??
           5.2.1. 1+1 Sparing, Withdrawal of ASP, Backup Override ...105
           5.2.2. 1+1 Sparing, Backup Override ......................105

**Comment by jaimecasero** [comment]
this seems to be related to current behavior 
"Override and there is already one ACTIVE, we leave this one
// as INACTIVE"
https://github.com/RestComm/jss7/blob/master/m3ua/impl/src/main/java/org/mobicents/protocols/ss7/m3ua/impl/AspStateMaintenanceHandler.java#L320

**Comment by jaimecasero** [comment]
In terms of configuration, do we need some new parameter to set the ApplicationServers in this new topology? or is just the FSM changes what we need?

**Comment by abhayani** [comment]
Jaime,

Sorry for delayed reasponse. I think its just matter of adding right FSM in AsImpl. Please find attached testcase and AsImpl fix that I believe is sufficient. 
[telscale-jss7-m3ua.patch.zip](https://github.com/RestComm/jss7/files/871338/telscale-jss7-m3ua.patch.zip)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/jss7/commit/73e9fc315c7357b9dc62b4583b76bfbdf732b9e6
