### ISSUE TITLE
Maven link seems broken

### ISSUE THREAD

**Issue by atesgoral** [RestComm/jss7#231]
https://oss.sonatype.org/content/repositories/releases/org/RestComm link that is mentioned in the [Maven Repository](https://github.com/RestComm/jss7#maven-repository) section of README.md gives a 404:

> **404 - Path /org/RestComm not found in local storage of repository "Releases" [id=releases]**
>
> Path /org/RestComm not found in local storage of repository "Releases" [id=releases]

**Comment by deruelle** [comment]
Thanks for reporting. Fixed
