### ISSUE TITLE
BER error on SRIforSM response with ver. 8.0.95?

### ISSUE THREAD

**Issue by kmmatwork** [RestComm/jss7#233]
Hi,

Tried the jss7 ver. 8.0.95 (from maven central) with our SMSC server. In the SRIforSM responses geneated using the library, there seems to be some extra bytes added which causes problems with decoding the SRIforSM response in the other end.

The result is that while we send a positive SRIforSM response back to the other end (other SMSCs) we don't receive the message itself, as the other end fails to decode the response.

With jss7 ver. 7.1.32 we don't get the same decoding problem and we get the message on a positive SRIforSM response.

In `wireshark` the SRIforSM response looks like the following (edited):

    Frame 118: 224 bytes on wire (1792 bits), 224 bytes captured (1792 bits)
    Linux cooked capture
    Internet Protocol Version 4, Src: 148.102.13.12, Dst: 213.10.151.18
    Stream Control Transmission Protocol, Src Port: 2907 (2907), Dst Port: 2906 (2906)
    MTP 3 User Adaptation Layer
    Signalling Connection Control Part
    Transaction Capabilities Application Part
    GSM Mobile Application
        Component: returnResultLast (2)
            returnResultLast
                invokeID: 1
                resultretres
                    opCode: localValue (0)
                        localValue: sendRoutingInfoForSM (45)
                    IMSI: 24201910390115
                        Mobile Country Code (MCC): Norway (242)
                        Mobile Network Code (MNC): Telenor Norge AS (01)
                    locationInfoWithLMSI
                        networkNode-Number: 917409003221
                    BER Error: This field lies beyond the end of the known sequence definition.
                        [Expert Info (Warning/Malformed): BER Error: Unknown field in Sequence]
                            [BER Error: Unknown field in Sequence]
                            [Severity level: Warning]
                            [Group: Malformed]

When highlighting the "BER Error:" line a "`00`" byte is highlighted in the "hexdump" window/area in `wireshark`.

Can send you the acual pcap dump by email and do additional tests if it is of interrest.

Fyi., when I tried the jss7 8.* series a few months ago, I think it was ver. 8.0.62 or thereabout, I got the same type of BER error on the SRIforSM request call. That call is now working fine! Instead I get the BER error on the SRIforSM response...

br,
kmm

**Comment by vetss** [comment]
Hello @kmmatwork 

SMSC GW does not work with JSS7 8.0, it works only with JSS7 7.*. The reason is SMSC GW demands some code update to fit new interfaces of JSS7 8.0. And we have not made it because JSS7 8.0 is not still released.

Please use JSS7 version 7.* so far.

**Comment by kmmatwork** [comment]
Thank you for the answer! Then we'll continue with using ver. 7.* until ver. 8.* has been officially released.

**Comment by vetss** [comment]
ok, I am closing the issue.
