### ISSUE TITLE
New M3UA feature

### ISSUE THREAD

**Issue by SummaNetworks** [RestComm/jss7#241]
For M3UA, there is no option to be able to configure a dynamic routing context, so that is negotiated on the beginning of the establishment.

**Comment by deruelle** [comment]
@SummaNetworks do you wan to contribute this one ?

**Comment by knosach** [comment]
doc about it https://www.ietf.org/rfc/rfc3332.txt

**Comment by knosach** [comment]
closed by https://github.com/RestComm/jss7/commit/ef9a336b98f7a50b9547c2461306e174f5743209

**Comment by gsaslis** [comment]
@knosach you mean this is now supported / implemented, right?

Do we have a link to some docs?
