### ISSUE TITLE
IMSI format for updateLocation

### ISSUE THREAD

**Issue by SigPloiter** [RestComm/jss7#254]
hello, wanted to know the IMSI format is changed from its e212 to e.164 format when declaring it as a GlobalTitle to be used in updatelocation

**Comment by SigPloiter** [comment]
i mean to be set as the calledparty address

**Comment by vetss** [comment]
Hello @SigPloiter 

I do not fully understand your question. Please explain more if you still have the question.

**Comment by knosach** [comment]
hi @SigPloiter 
* IMSI is used in UpdateLocationRequest (MAP protocol) packet as you can see here: https://github.com/RestComm/jss7/blob/71f24a37a2e313524084149696a1efd791b07cba/map/map-impl/src/main/java/org/mobicents/protocols/ss7/map/service/mobility/locationManagement/UpdateLocationRequestImpl.java#L73
Addresses are set when you are creating a new dialog : 
https://github.com/RestComm/jss7/blob/71f24a37a2e313524084149696a1efd791b07cba/map/map-impl/src/main/java/org/mobicents/protocols/ss7/map/service/mobility/MAPDialogMobilityImpl.java#L174

Hope this helps.
BR
