### ISSUE TITLE
TCAP: allow TCAP user specify ability to skip protocol version in dialogue portion

### ISSUE THREAD

**Issue by okulikov** [RestComm/jss7#258]
Currently this option is available as property of the entire `TCAPstack` . It is more convenient to get ability to specify this option from the higher level then TCAP for the case when the same stack is used for dialogs with both options.

**Comment by vetss** [comment]
Hello @okulikov 

this is a tcap stack option "tcap set donotsendprotocolversion".
Do you want to contribute it ?

**Comment by okulikov** [comment]
@vetss yes, will do

**Comment by knosach** [comment]
merged pull request, going to add test for this feature

**Comment by knosach** [comment]
closed by https://github.com/RestComm/jss7/commit/58afaad3821369c77f6be9203c7419ee1c9f5b25
and https://github.com/RestComm/jss7/commit/d41540d41ffbaa986232112e59257cdda5aeacf8
