### ISSUE TITLE
SMS "Space" Encoding

### ISSUE THREAD

**Issue by SigPloiter** [RestComm/jss7#266]
Hello, am using the latest binary release 7.3.1398, upon creating an SMS string content as a user input saved in a variable, anything after the space is terminated. while if hardocding the string as a parameter in UserData and including spaces in it its encoded properly and nothing is terminated, please advise

**Comment by vetss** [comment]
Hello @SigPloiter can you provide some code example that can help of reproduce a problem ?

**Comment by SigPloiter** [comment]
@vetss thanks for your reply, please find the client side code 

below are the used hardcoded parameters on client side code
client pc:1
server pc:2
client IP:192.168.56.101
client port:2905
server IP:192.168.56.102
server port:2906
Target's MSC: 201512345678

[MTForwardSMS.java.zip](https://github.com/RestComm/jss7/files/1371801/MTForwardSMS.java.zip)
[MTSMSLowLevel.java.zip](https://github.com/RestComm/jss7/files/1371803/MTSMSLowLevel.java.zip)

**Comment by SigPloiter** [comment]
here are the server side code
[MTForwardSMSLowLevel.java.zip](https://github.com/RestComm/jss7/files/1371809/MTForwardSMSLowLevel.java.zip)
[MTForwardSMSResp.java.zip](https://github.com/RestComm/jss7/files/1371810/MTForwardSMSResp.java.zip)

**Comment by SigPloiter** [comment]
Dear Sergey, any luck ? Everything clear in the code ?

**Comment by SigPloiter** [comment]
@vetss tell me if you need more info to reproduce this error

**Comment by SigPloiter** [comment]
@vetss i figured out the issue, nothing concerns jss7, misimplementation from my side
thanks

**Comment by ayarifak** [comment]
@SigPloiter  its great job but i want attack real server use ss7 to get real resul how can i find server please help me

**Comment by SigPloiter** [comment]
i believe its better to open an issue on sigploit

**Comment by ayarifak** [comment]
@SigPloiter 
i think u can broth

**Comment by ayarifak** [comment]
@SigPloiter u can help me befor do it

**Comment by vetss** [comment]
Hello @SigPloiter 

do you mean that provided by you code does not need to be analized because your issue was solved ?

**Comment by SigPloiter** [comment]
Yes , thanks :)
