### ISSUE TITLE
org.mobicents.protocols.ss7.map.load.Client always initiates 2000 dialogs even when parameter set to 1

### ISSUE THREAD

**Issue by abdulazizali77** [RestComm/jss7#268]
It seems to be the `endCount` set to `-100` and the mod equation at
https://github.com/RestComm/jss7/blob/1d4454e70f3bc5cb6e3d6d6fa00340e7550be1c1/map/load/src/main/java/org/mobicents/protocols/ss7/map/load/Client.java#L707

Setting `endCount` to 0 seems to fix it, but am unsure what the ramifications to load testing rampup time might be
https://github.com/RestComm/jss7/blob/1d4454e70f3bc5cb6e3d6d6fa00340e7550be1c1/map/load/src/main/java/org/mobicents/protocols/ss7/map/load/Client.java#L125

@vetss Sergey, do you think this should/could be changed?
The basic use case is we want to use the load tester for non-load purposes, sending 1 dialog or very small amount of dialogs to check health of GW.

**Comment by vetss** [comment]
Fixed in https://github.com/RestComm/jss7/pull/269
by: 
https://github.com/RestComm/jss7/commit/b92e230f354d14b41897fa7fb725ec2711533033
