### ISSUE TITLE
http status 501

### ISSUE THREAD

**Issue by zidanekeren** [RestComm/jss7#270]
Hi guys.

first of all. im completely new with this.
so im clueless... :(

im trying to configure for gmlc, and when im doing some testing, i've got this error message.

HTTP Status 501 -
type Status report
message
description The server does not support the functionality needed to fulfill this request ().

can you guys help / guide me to solve this issue?
thanks

**Comment by FerUy** [comment]
Hi @zidanekeren, I'm afraid we'll need more details to help you.

**Comment by FerUy** [comment]
By the way, please post this kind of questions in Restcomm Google group https://groups.google.com/forum/#!forum/restcomm thru email or in https://gitter.im/RestComm/gmlc. To open issues for GMLC in GitHub, please use https://github.com/RestComm/gmlc.
