### ISSUE TITLE
how could i just use map smservice ? should i must use sctp protol?(i'm newer to 3gpp protol )

### ISSUE THREAD

**Issue by apri30th** [RestComm/jss7#274]
i have seen the example in org.mobicents.protocols.ss7.map.load.client

here is my question,  did i must init  sctp m3ua sccp tcap before init map?

if so , in method sctpManagement.addAssociation(CLIENT_IP, CLIENT_PORT, SERVER_IP, SERVER_PORT....) the server_Ip , server_port  i guess they are remote service's ip (like hss /hls/smsc) and port . am i right? 

if not , maybe  i can just use sccp like org.mobicents.protocols.ss7.map.funcional.MAPFunctionalTest use ?   but if so , how could i set the server ip and port in sccpAddress?  in a other way ,if so , how can i connect remote server like(hls /hss /smsc)?

can anyone help me?

**Comment by knosach** [comment]
hi @apri30th 
1) you must init and start SCTP,M3UA etc. before MAP
2) yes you are right
you can find more info in doc [here](http://documentation.telestax.com/core/ss7/SS7_Stack_User_Guide.html#_configuring_standalone)
