### ISSUE TITLE
M3UA silently hides transmission exception

### ISSUE THREAD

**Issue by okulikov** [RestComm/jss7#276]
In case when M3UA has no suitable AS for message transmission it logs error and silently exits so there is no difference between normal and failed transmission.

**Comment by okulikov** [comment]
PR https://github.com/RestComm/jss7/pull/86

**Comment by vetss** [comment]
Hello @okulikov 

I have added your commit to the master branch.
https://github.com/RestComm/jss7/commit/c766ad33617651eb9cf0bfc761a395181d130dd9
Thanks for the update.
