### ISSUE TITLE
Problem in running Map Client

### ISSUE THREAD

**Issue by ghalizadeh** [RestComm/jss7#282]
Dear All,

I get the JSS7 from GitHub and build it successfully.I set all parameters in the build.xml but when I run the client with "ant client" command, unfortunately I get the following errors:
Could you please kindly give me some advice.

[java] IpChannelType=SCTP
     [java] CLIENT_IP=172.20.12.207
     [java] CLIENT_PORT=8011
     [java] SERVER_IP=10.200.19.66
     [java] SERVER_PORT=11204
     [java] CLIENT_SPC=194
     [java] SERVET_SPC=110
     [java] NETWORK_INDICATOR=3
     [java] SERVICE_INIDCATOR=3
     [java] SSN=8
     [java] ROUTING_CONTEXT=100
     [java] DELIVERY_TRANSFER_MESSAGE_THREAD_COUNT=16
     [java] RAMP_UP_PERIOD=-100
     [java] SCCP_CLIENT_ADDRESS=1111112
     [java] SCCP_SERVER_ADDRESS=9960639999
     [java] ROUTING_INDICATOR=ROUTING_BASED_ON_GLOBAL_TITLE
     [java] NDIALOGS=6000
     [java] MAXCONCURRENTDIALOGS=100
     [java] Input Stream = sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@241bee6f
     [java] 0    [main] WARN  org.mobicents.protocols.sctp.netty.NettySctpManagementImpl  - Failed to load the SCTP configuration file.
     [java] /root/reza/JSS7/JSS7-4/jss7/map/load/client/Client_sctp.xml (No such file or directory)
     [java] 150  [main] WARN  org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl-MapLoadClientSccpStack  - Failed to load the Sccp Management configuration file.
     [java] /root/reza/JSS7/JSS7-4/jss7/map/load/client/MapLoadClientSccpStack_management2.xml (No such file or directory)
     [java] 224  [main] WARN  org.mobicents.protocols.ss7.tcap.TCAPStackImpl-Test  - Failed to load the TCAP Management configuration file.
     [java] /root/reza/JSS7/JSS7-4/jss7/map/load/client/Test_management.xml (No such file or directory)
     [java] 403  [main] WARN  org.mobicents.protocols.ss7.sccp.impl.SccpProviderImpl  - Registering SccpListener=org.mobicents.protocols.ss7.tcap.TCAPProviderImpl@6c9f3578 for already existing SccpListnere=org.mobicents.protocols.ss7.tcap.TCAPProviderImpl@6c9f3578 for SSN=8
     [java] 10614 [Sctp-BossGroup-Client-1-1] WARN  org.mobicents.protocols.sctp.netty.NettySctpClientHandler  - ChannelUnregistered event: association=Association [name=clientAsscoiation, associationType=CLIENT, ipChannelType=SCTP, hostAddress=172.20.12.207, hostPort=8011, peerAddress=10.200.19.66, peerPort=11204, serverName=null, extraHostAddress=[]]
     [java] 20620 [Sctp-BossGroup-Client-1-1] WARN  org.mobicents.protocols.sctp.netty.NettySctpClientHandler  - ChannelUnregistered event: association=Association [name=clientAsscoiation, associationType=CLIENT, ipChannelType=SCTP, hostAddress=172.20.12.207, hostPort=8011, peerAddress=10.200.19.66, peerPort=11204, serverName=null, extraHostAddress=[]]

the following config files in"/root/reza/JSS7/JSS7-4/jss7/map/load/client" are created automatically:
Client_sctp.xml
Client_m3ua1.xml
Test_management.xml
MapLoadClientSccpStack_sccprouter2.xml
MapLoadClientSccpStack_sccpresource2.xml

Regards,

**Comment by knosach** [comment]
hi @ghalizadeh 

please follow next instruction https://github.com/RestComm/jss7/blob/master/map/load/README.txt
1) ant clean
2) ant assemble
3) ant client

BR

**Comment by ghalizadeh** [comment]
Dear Knosach,
Thanks for your considerations and supports.
I already follow this instruction but I get the mentioned errors.
also I check and do all instructions from begin to end.

the first error is "No such file or directory" while the file are exists.

the second error is 👍 WARN org.mobicents.protocols.ss7.sccp.impl.SccpProviderImpl - Registering SccpListener=org.mobicents.protocols.ss7.tcap.TCAPProviderImpl@6c9f3578 for already existing SccpListnere=org.mobicents.protocols.ss7.tcap.TCAPProviderImpl@6c9f3578 for SSN=8

and the last error:
WARN org.mobicents.protocols.sctp.netty.NettySctpClientHandler - ChannelUnregistered event: association=Association [name=clientAsscoiation, associationType=CLIENT, ipChannelType=SCTP, hostAddress=172.20.12.207, hostPort=8011, peerAddress=10.200.19.66, peerPort=11204, serverName=null, extraHostAddress=[]]

Could you please kindly check them.

Regards.

**Comment by gsaslis** [comment]
@ghalizadeh sounds like a weird error what you're describing: 

> the first error is "No such file or directory" while the file are exists.

maybe if you can share the exact steps and logs (using [GitHubGist](https://gist.github.com/) ), we can spot something you're doing wrong there?
