### ISSUE TITLE
SCTP link to server can not be up

### ISSUE THREAD

**Issue by ghalizadeh** [RestComm/jss7#283]
# Dear all
## and whenever I get this error , my SCTP link to server cannot be established.

 [java] 10830 [Sctp-BossGroup-Client-1-1] WARN  
org.mobicents.protocols.sctp.netty.NettySctpClientHandler  -# ChannelUnregistered event: association=Association [name=clientAsscoiationX4, associationType=CLIENT, ipChannelType=SCTP, hostAddress=172.20.12.207, hostPort=8014, peerAddress=10.208.19.67, peerPort=11205, serverName=null, extraHostAddress=[]]

**But sometimes restarting the server will solve the problem but sometimes not.**
Regards

**Comment by knosach** [comment]
hi @ghalizadeh 
this error occurs when a client can not establish a connection to the server. Can you check is this port open (11205) on the server side when you getting this error? Also you can check your SCTP connection between hosts via sctp testing tool `sctp_darn`

BR

**Comment by ghalizadeh** [comment]
**Dear @knosach 
By using sctp_darn, I get the following error:**

[root@vlr-lsn ~]# sctp_darn -H 172.20.12.207 -P 8014 -h 10.200.19.67 -p 11205 -s
sctp_darn ready to send...
172.20.12.207:8014-10.200.19.67:11205> 1
Recieved SCTP_CANT_STR_ASSOC
No association is present now!!
172.20.12.207:8014-10.200.19.67:11205>

**Comment by alexsiege** [comment]
@ghalizadeh Hi, Check these links for your issue : 

https://books.google.co.uk/books?id=ptSC4LpwGA0C&pg=PA282&lpg=PA282&dq=%22SCTP_CANT_STR_ASSOC%22&source=bl&ots=Kt1EUjcpNo&sig=wfA4No7Xre9j8yZX_JLAn-iBIPU&hl=en&sa=X&ved=0ahUKEwiax82F1JHZAhVLDcAKHWttAmAQ6AEIPzAE#v=onepage&q=%22SCTP_CANT_STR_ASSOC%22&f=false
http://petanode.com/blog/posts/sctp-notifications-in-linux.html

**Comment by knosach** [comment]
@ghalizadeh I believe it is an issue on 10.200.19.67. You should try another server for test

**Comment by ghalizadeh** [comment]
**Dear @knosach 
On the basis of tcpdump results, I send [INIT] message two times then I get the [INIT ACK] but unfortunately I [ABORT] it !!!**

My IP-Port -> 172.20.12.207:8011
The SPS(STP) IP-Port -> 10.200.19.66:11204
TCPDUMP output:
14:13:02.530881 IP (tos 0x2,ECT(0), ttl 64, id 0, offset 0, flags [DF], proto SCTP (132), length 120)
    172.20.12.207.8011 > 10.200.19.66.11204: sctp (1) [INIT] [init tag: 1848570270] [rwnd: 131072] [OS: 10] [MIS: 65535] [init TSN: 3408781919]
14:13:02.531722 IP (tos 0x2,ECT(0), ttl 64, id 0, offset 0, flags [DF], proto SCTP (132), length 120)
    172.20.12.207.8011 > 10.200.19.66.11204: sctp (1) [INIT] [init tag: 1848570270] [rwnd: 131072] [OS: 10] [MIS: 65535] [init TSN: 3408781919]
14:13:02.541825 IP (tos 0xc0, ttl 251, id 65456, offset 0, flags [none], proto SCTP (132), length 788)
    10.200.19.66.11204 > 172.20.12.207.8011: sctp (1) [INIT ACK] [init tag: 3816703152] [rwnd: 820448] [OS: 17] [MIS: 10] [init TSN: 3816703152]
14:13:02.541877 IP (tos 0x2,ECT(0), ttl 64, id 0, offset 0, flags [DF], proto SCTP (132), length 36)
    172.20.12.207.8011 > 10.200.19.66.11204: sctp (1) [ABORT]
14:13:02.541921 IP (tos 0xc0, ttl 251, id 65457, offset 0, flags [none], proto SCTP (132), length 788)
    10.200.19.66.11204 > 172.20.12.207.8011: sctp (1) [INIT ACK] [init tag: 2741701418] [rwnd: 820448] [OS: 17] [MIS: 10] [init TSN: 2741701418]
14:13:02.541940 IP (tos 0x2,ECT(0), ttl 64, id 0, offset 0, flags [DF], proto SCTP (132), length 36)
    172.20.12.207.8011 > 10.200.19.66.11204: sctp (1) [ABORT]

**Comment by knosach** [comment]
hi @ghalizadeh I have two questions:
1) do you use  sctp_darn as the test server if not please use it?
2) can you send pcap files from both sides for analysis?
BR

**Comment by ghalizadeh** [comment]
Dear @knosach
1-do you use sctp_darn as the test server if not please use it?
I don't have access to the server side because that's critical and comercial node (SPS) and just our vendor could login to its OS, therefore, I cannot run sctp_darn command on the server terminal to create a listener 
I only can run sctp_darn on my client in sending mode that I sent its logs and result

2-can you send pcap files from both sides for analysis?
Please find this file from client side (because I don't have access to server side) as enclosed file
[pcap.zip](https://github.com/RestComm/jss7/files/1713412/pcap.zip)
Best Regards,
Alizadeh

**Comment by nhanth87** [comment]
Hello,
In case of customer support and 24/7. I think you should request a professional support insteal of waiting for community support.
You can request it from https://accounts.restcomm.com/registration.jsp
