### ISSUE TITLE
TCAPID byte swapping

### ISSUE THREAD

**Issue by faizann** [RestComm/jss7#293]
**FEATURE REQUEST**:

**What happened**:

TCAPStack swaps bytes to change the endianess of the TCAPID. This makes it difficult to match TCAPID for routing in STPs. Some STPs expect TCAPID to be in little endian and such byte swapping makes it impossible to match TCAPIDs within a range.

**What you expected to happen**:

TCAPID if left unchanged (unswapped) matches the TCAPID range on the STP.

**How to reproduce it (as minimally and precisely as possible)**:

We can see that in the traces that the most significant byte is on the right side of the TCAPID OCTET STRING.

**Anything else we need to know?**:

**Environment**:
- Restcomm JSS7 version (from startup logs): 7.x and 8.x 
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Deployment method (e.g. application server version + config + method): N/A
- Others:N/A

** Proposed Feature **:

We would prefer a configurable flag that enables/disables this byte swapping feature of TCAP Stack. 
The code change is very minimum and requires change in utils.java to accept a flag to swap or not-swap the bytes.

```
    public static long decodeTransactionId(byte[] data) {
        byte[] longRep = new byte[8];
        // copy data so longRep = {0,0,0,...,data};
        System.arraycopy(data, 0, longRep, longRep.length - data.length, data.length);
        ByteBuffer bb = ByteBuffer.wrap(longRep);
        return bb.getLong();

    }

    public static byte[] encodeTransactionId(long txId) {
        // txId may only be up to 4 bytes, that is 0xFF FF FF FF
        byte[] data = new byte[4];
        // long ll = txId.longValue();
        // data[3] = (byte) ll;
        // data[2] = (byte) (ll>> 8);
        // data[1] = (byte) (ll>>16);
        // data[0] = (byte) (ll >> 24);
        data[3] = (byte) txId;
        data[2] = (byte) (txId >> 8);
        data[1] = (byte) (txId >> 16);
        data[0] = (byte) (txId >> 24);

        return data;
    }
```

**Comment by gsaslis** [comment]
Adding an extra flag sounds like a valid approach.

@messaging-squad what do you think?

**Comment by knosach** [comment]
hi @	faizann will you be able to create PR for this issue?

**Comment by faizann** [comment]
Hi @knosach  Yes. Already working on it and should be done by end of this week.

**Comment by knosach** [comment]
closed in https://github.com/RestComm/jss7/commit/da9d007c32b1eca6157d4addaecbe3d626da8d07
closed in https://github.com/RestComm/jss7/commit/66b66860a794e284524fcf47b87566904179eaff
