### ISSUE TITLE
SCTP / SCCP parameters modifying issues

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#294]
Testing brought me following issues:

1) CLI : all parameters except of <id> and <ass/server-name>must be with prefix
example: command
```sccp sap modify <id> <mtp3-id> <opc> <ni> stackname <stack-name> networkid <networkId>	localgtdigits <localGtDigits>```
has parameter withiut name: <mtp3-id> <opc> <ni>
we need to have the syntax:
```sccp sap modify <id> mtp3-id <mtp3-id> opc <opc> ni <ni> stackname <stack-name> networkid <networkId>	localgtdigits <localGtDigits>```

or

```sccp address modify <id> <address-indicator> <point-code> <subsystem-number> <translation-type> <numbering-plan> <nature-of-address-indicator> <digits> stackname <stack-name>```
->
```sccp address modify <id> address-indicator <address-indicator> point-code <point-code> subsystem-number <subsystem-number> translation-type <translation-type> numbering-plan <numbering-plan> nature-of-address-indicator <nature-of-address-indicator> digits <digits> stackname <stack-name>```
The target is - we will be able to change only one parameter. Same for SCTP part

2) GUI: we may not change sccociation / server name / sccp object ID (fields must be disabled for editing). For an asociation it is allowed even to show an updating form for a started association.
Specially for SCTP Association - we can not change SERVER / CLIENT type (a disabled field must be)

3) SCTP GUI - we can not modify non-stopper servers / associations but it does not clear from GUI (even no error messages). We need to make buttons "Mofify" disabled (grey) when a server / association is started

4) SCTP GUI: it is invoked only "ModifyAssociation" and not invoked "ModifyServerAssociation" when an association is server type

5) GUI SCTP:  when assiciation changing it gives error like "there is already an association with same local / remote address / port". When checking this we must skip of checking of updating assocoation, only other associations

6) GUI SCCP: it is blocked to specify of SSN==0 for a creating/modifying (we need to update a JMX module part), we need toa loow it as it is done for CLI for any AI value. It must be allowed (but SPC for an address must be >0 !!)

**Comment by knosach** [comment]
modifying for SCTP with possibility change only one parameter was implemented in https://github.com/RestComm/jss7/issues/72

**Comment by knosach** [comment]
about 4: there is `modifySctpServerAssociation` and `modifySctpAssociation` in `function modifyAssoc(name)`

**Comment by knosach** [comment]
final commit https://github.com/RestComm/sctp/commit/f833472b6702bc5d3e56e8668e7743727cf6e62b
