### ISSUE TITLE
Allow USSDString to be null

### ISSUE THREAD

**Issue by okulikov** [RestComm/jss7#298]
At the moment when incoming message due to some reasons does not contain `ussdString` parameter MAP parser throws appropriate parsing exception. This exception then pop-up other exceptions till the underlying SCCP layer. This is not convenient because in sense of SCCP message is properly formatted and it contains sufficient information to handle it at MAP layer.

Instead of throwing parsing exception would be better to leave `ussdString` as `null` so application can do  check on its own way and handle this accident gracefully using successfully decoded information.

**Comment by knosach** [comment]
hi @okulikov we can not leave ussdString as null because it breaks specification : if `USSD Data Coding Scheme` parameter is present, then the `USSD String' parameter has to be present. So I will reject your PR.

**Comment by okulikov** [comment]
@knosach The specification is completed and final. The goal is to communicate with legacy equipment where this is a real use case rather then investigating specs.
