### ISSUE TITLE
SRI Response

### ISSUE THREAD

**Issue by hoanbeto** [RestComm/jss7#3]
I have a problem with SRIResponse: TCAP cannot decode exactly and unrecognize this input packet.
Here is log:
"200 ERROR [org.mobicents.protocols.ss7.tcap.DialogImpl] (pool-27-thread-1) Rx : ReturnResultLast[invokeId=1, operationCode=OperationCode[OperationType=Local, data=22], parameter=Parameter[data=[........................], parameters=null, primitive=false, tag=3, tagClass=2, encodingLength=104]] but there is no corresponding Invoke"

Please show me where i'm wrong?

**Comment by vetss** [comment]
"but there is no corresponding Invoke" - this means that
1) the response came too late and the original Invoke was timedout
2) there is some error in a customer's code
