### ISSUE TITLE
Missed jss7-management-console and SCCP Address&Rule settings through CLI (checked release 8.0.0-179)

### ISSUE THREAD

**Issue by BarbosSergos** [RestComm/jss7#303]
kind bug

**What happened**: 
1. After the build, the target doesn't contain oam/ folder, which includes jss7-management-console.war and jolokia.war, as a result, we don't have jss7-management-console, only CLI.
2. In CLI missed settings for "address" and "rule". Available only these settings:
restcomm(local)>sccp
sap     dest    rsp     rss     lmr     csp     set     get     --help

**What you expected to happen**:
1. Expected to have jss7-management-console
2. Expected to configure sccp address and sccp rule.

**How to reproduce it (as minimally and precisely as possible)**:
Build and deploy release 8.0.0-179.

**Anything else we need to know?**:

**Environment**:
- Restcomm JSS7 version (from startup logs): 8.0.0-179
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux loadtest 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Deployment method (e.g. application server version + config + method): wildfly-10.1.0.Final + standalone + ant deploy
- Others:

**Comment by nperez-messagebird** [comment]
For what it is worth, I am too researching this and found it was removed in this commit: 3d5f5c7bceb14b4839b6f1728bce56fdd7e01779

I can only assume they intended to move that functionality somewhere else, but no real indication of where. I guess that is why the release script for smpp-extensions still references a 7.4.0 tag.

**Comment by nhanth87** [comment]
Hello,
Please use version 7.x, in the version 8.x telestax team remove some old features (like sccp rule/address create and modify), the team trying to rewrite it with some enhancement based on jboss wildfly. But it's not finish now

Br,
TN
