### ISSUE TITLE
RestComm-jss7 CAP: Bulk IDP request 

### ISSUE THREAD

**Issue by armachea** [RestComm/jss7#310]
Hi guys,

i am trying to send a large quantity of IDP based on CAP protocol with (Restcomm-JSS7 simulator) but it's not working ..... I have changes the source file and included a loop in /home/admin/Documents/ss7-simREPO/jss7-master/tools/simulator/core/src/main/java/org/restcomm/protocols/ss7/tools/simulator/tests/cap/TestCapSsfMan.java
( in the function performInitialDp )
But still cant get it to work..... Can anyone show me the way to do it

Br

**Comment by yulianoifa-mobius** [comment]
Hi
Please use https://groups.google.com/forum/#!forum/mobicents-public
Or request commercial support for support enquiries
