### ISSUE TITLE
RuleComparator Issue

### ISSUE THREAD

**Issue by vinhdhqdce** [RestComm/jss7#315]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 kind bug

**What happened**:

In the class org.mobicents.protocols.ss7.sccp.impl.router.RuleComparator

The function comapreLength.

`
        if (digits1.length() == digits2.length()) {
            return 0;}`

Because it return 0 then in some case, the rulesMap is not correct in order

example config: [Test_sccprouter2.txt](https://github.com/RestComm/jss7/files/3635845/Test_sccprouter2.txt)
The rule ID = 22 MUST be above the rule with ID = 2 because they have the same called digits = "326" and the rule ID = 22 has pattern calling digit, and in the rule ID = 2 is null. But with this Comparator, the rule with ID = 2 allway on top in this case

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Remove the condition digits1.length() == digits2.length() or just return digits1.compareTo(digits2)

**Anything else we need to know?**:

**Environment**:

- Restcomm JSS7 version (8.0.xxx):

**Comment by yulianoifa-mobius** [comment]
Hi
You may always change the id of the rules and as result receive the correct behaviour ( e.g setting the rule 2 id 2222 for example )
