### ISSUE TITLE
install ussd simulator

### ISSUE THREAD

**Issue by parsibox** [RestComm/jss7#319]
hi
how can i install ussd simulator on windows 10?

**Comment by nhanth87** [comment]
Hi,
You can't run it on windows because java on windows don't have support for sctp

Br,
TN

**Comment by parsibox** [comment]
so how can i install it on centos 7 64 bit

**Comment by nhanth87** [comment]
we have a wiki here https://github.com/RestComm/jss7/wiki/Build-jSS7-from-Source

**Comment by caiocf** [comment]
1) For Centos/Fedora you need install package SCTP on kernel.

$ yum instlal install lksctp-tools

2) Build Sources JSS7
 https://github.com/RestComm/jss7/wiki/Build-jSS7-from-Source

**Comment by parsibox** [comment]
i install it
how can i start jbosst ?
