### ISSUE TITLE
use multiple M3UA link

### ISSUE THREAD

**Issue by parsibox** [RestComm/jss7#326]
hi
how can i intigirate ussd client with multiple  M3UA link ?
i want use this code with multiple M3UA  link
https://github.com/RestComm/jss7/blob/master/map/load/src/main/java/org/restcomm/protocols/ss7/map/load/Client.java

**Comment by parsibox** [comment]
anyone?

**Comment by honphilemon** [comment]
Please I need link for this software

**Comment by nhanth87** [comment]
you need to add multi-tenancy and it will support multi m3ua link, but you also need to route those messages to correct networkId
