### ISSUE TITLE
How to get source association from incoming MAP request?

### ISSUE THREAD

**Issue by myrza-evgeniy** [RestComm/jss7#333]
Hello, guys. I want to know if there is any way to get the source association data. For example, how to get source IP and source port (source association data) from incoming MAP messages like SRI-SM-Request, MT-FSM-Request?

**Comment by nhanth87** [comment]
You can't get it because it's happening at the SCTP layer, at MAP protocol, you can't see those infomations

**Comment by myrza-evgeniy** [comment]
> You can't get it because it's happening at the SCTP layer, at MAP protocol, you can't see those infomations

Maybe there are some indirect ways to get this information?
I can get DPC and OPC from SRI-SM-Request/MT-FSM-Request. 
From DPC/OPC pair can receive M3UA Route. 
M3UA Route has relation with Applcation Server.
Applcation Server has relation with ASP Factory.
ASP Factory has relation with association.

but here we have case when one Application Server will related with many ASP Factories

**Comment by nhanth87** [comment]
if you can control all the below layers then yes, if you can't then no

**Comment by nhanth87** [comment]
you may need to understand why MAP layer there
in the beginning, there's no IP

**Comment by myrza-evgeniy** [comment]
> if you can control all the below layers then yes, if you can't then no

For project we need to get source IP from incoming MAP messages for additional filtering in our business logic.
