### ISSUE TITLE
Bug in GUI - sctpExtraHostAddress list for SCTP server is not set as empty after empty String

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#37]
If we are creating via GUI a new SCTP server if we leave "Extra Host Address" field empty sctpExtraHostAddress then extraHostAddresses will created with a single empty memebr, but must be empty.

To solve it we need to check in SctpManagementJmx.addSctpServer() method - check if the String extraHostAddresses value is null OR EMPTY and in both cases create an empty array.

We need to update both branches - master and netty-2 !!!

**Comment by nhanth87** [comment]
Hi Sergey,
this function also need to change:
    public Association addSctpAssociation(String hostAddress, int hostPort, String peerAddress, int peerPort, String assocName,
            IpChannelType ipChannelType, String extraHostAddresses) throws Exception {
        this.wrappedSctpManagement.addAssociation(hostAddress, hostPort, peerAddress, peerPort, assocName, ipChannelType,
                extraHostAddresses != null ? extraHostAddresses.split(",") : null);
        return null;
    }

**Comment by vetss** [comment]
Fixed by
https://github.com/RestComm/jss7/commit/d84f88b7379e7a51b1d987575425176cbc333927
