### ISSUE TITLE
Implement MAP-ANY-TIME-SUBSCRIPTION-INTERROGATION

### ISSUE THREAD

**Issue by abhayani** [RestComm/jss7#4]
Implement the AnyTimeSubscriptionInterrogationRequest interface and complete the operation.

**Comment by vgsub** [comment]
Hello, could you please tell me if ATSI operation is on roadmap and would be implemented in the near future? As I understand it's single way to get O-CSI and determine GTscf to send IDP.

Regards,
Vadim

**Comment by nhanth87** [comment]
Hi @vgsub we have planed it but due to some reasons, it can't come in next month.

Do you want to contribute for this issue?

Br,
TN

**Comment by vgsub** [comment]
Hi @nhanth87. Sorry for the late response. Yes, I've implemented ATSI Req/Res and sending/receiving on this week. Also I've tested it with my little scf/ssf program - all works fine, message fields are encoded and decoded correctly. So I can share this code. 

I'm newly on GitHub, so I don't know anything about commiting process here. Can you explain me how can I commit this code?

Thanks and regards,
Vadim

**Comment by nhanth87** [comment]
Hi @vgsub,
Thanks for your info 👍 

Can you please sign http://www.telestax.com/open-source/#Contribute

Then please read [Open Source Playbook](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.wm9l5oonx5ox)

Shortly: 
fork jss7 project to your account, 
make a change
create a pull request and attach diff with this PR

BR,
TN

**Comment by vetss** [comment]
I have created the issue for it. When I did it I forgot of this issue. I am closing this issue now. Let's continue work in
https://github.com/RestComm/jss7/issues/108

**Comment by deruelle** [comment]
Thanks @vgsub. Contribution acknowledged at https://telestax.com/acknowledgements/ !
