### ISSUE TITLE
GUI: SCTP Server Stop tool tip display error in GUI

### ISSUE THREAD

**Issue by FerUy** [RestComm/jss7#40]
Please view attached image, where the tip displays the opposite message the button is meant to achieve.
![jss7-gui-sctp_server_stop_tooltip-error](https://cloud.githubusercontent.com/assets/14883482/13724408/8d3703dc-e863-11e5-909f-960e6d020bbf.png)

**Comment by vetss** [comment]
Fixed by
https://github.com/RestComm/jss7/commit/d207176f748080aaa09a282c0492995cd34daefa
