### ISSUE TITLE
GUI: M3UA ASP Stop tool tip display error in GUI

### ISSUE THREAD

**Issue by FerUy** [RestComm/jss7#41]
Please view attached image where the button tip advises about the opposite action is meant to achieve.
![jss7-gui-m3ua_asp_stop_tooltip_error](https://cloud.githubusercontent.com/assets/14883482/13726046/3f66cd64-e894-11e5-89ff-ce1256e36540.png)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/jss7/commit/8bc61f5ea23a9cbe5045e41464c8588422184bd1
