### ISSUE TITLE
MAP load test need to support GT routing for real world test

### ISSUE THREAD

**Issue by nhanth87** [RestComm/jss7#47]
MAP load test just support PC + SSN routing, so it can't be used to test USSD GW.

**Comment by nhanth87** [comment]
Attached here is example of map load client that using GT instead of SSN
[Client.txt](https://github.com/RestComm/jss7/files/353756/Client.txt)

**Comment by knosach** [comment]
closed by https://github.com/RestComm/jss7/commit/e81829d43bf01206bf6b443ef6f9a0e4d7b7eca8

**Comment by nhanth87** [comment]
hi knosach,
why do you close this ticket? in the path #e81829d it's just changed some parameter.
We need routing base on GT, not SSN + PC

Please keep this ticket open for contributor/sponsor

Br,
TN

**Comment by knosach** [comment]
@nhanth87 
global titles and routing based type has been added as parameters , so now they are configurable for script
see here : https://github.com/RestComm/jss7/commit/e81829d43bf01206bf6b443ef6f9a0e4d7b7eca8#diff-ed7f427e28773d4863c1f4eff9461035R167

**Comment by nhanth87** [comment]
Don't close the ticket,
it's SCCP layer. GT routing has happened at M3UA layer.

your new code is based on PC + SNN routing, see

```
+    protected static RoutingIndicator ROUTING_INDICATOR = RoutingIndicator.ROUTING_BASED_ON_DPC_AND_SSN;
```

We need RoutingIndicator.ROUTING_BASED_ON_GLOBAL_TITLE

Br,
TN

**Comment by knosach** [comment]
@nhanth87 it is set here from configuration : 
https://github.com/RestComm/jss7/blob/e81829d43bf01206bf6b443ef6f9a0e4d7b7eca8/map/load/src/main/java/org/mobicents/protocols/ss7/map/load/Client.java#L427

If you have any other questions contact please contact me on slack
