### ISSUE TITLE
GUI: LMR creation not working

### ISSUE THREAD

**Issue by FerUy** [RestComm/jss7#52]
When attempting to create a LMR, an exception is thrown in the console ([ERROR] java.lang.IllegalArgumentException : No enum constant org.mobicents.protocols.ss7.sccp.LongMessageRuleType.LongMessagesForbidden) and the LMR creation obviously fails.
Moreover, at creation attempt, the text for the <long-message-rule-type> parameter is replaced by "Load Sharing Algorithm" (reminding the SCCP rule "loadsharing-algo" parameter). See image and error full stack trace attached below:
[LMR_create_GUI_fullStackTrace_error.txt](https://github.com/RestComm/jss7/files/178121/LMR_create_GUI_fullStackTrace_error.txt)
![jss7_gui_lmr_creation_loadsharingalgo_instead_of_lmrtype_](https://cloud.githubusercontent.com/assets/14883482/13850584/5451e6ac-ec39-11e5-8b97-496ec8569884.png)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/jss7/commit/3a37b776dcdf267c0d2d74b70b6587ed6f11aace
https://github.com/RestComm/jss7/commit/62610b1aa319b3fe864496e8ccf2cc779c1d1cad
https://github.com/RestComm/jss7/commit/2ca4c8f66965fece66220c28eee4c6b99bd7ce84
