### ISSUE TITLE
build failure - jss7/sgw/boot/target/mobicents-sgw/native does not exist

### ISSUE THREAD

**Issue by jaroszan** [RestComm/jss7#6]
BUILD FAILED
    /home/user/installs/jss7/release/build.xml:104: /home/user/installs/jss7/sgw/boot/target/mobicents-sgw/native does not exist.

This folder is missing also in 

    jss7/release/target/mobicents-jss7-dist/ss7/mobicents-ss7-sgw/

However it is present in mobicents-ss7-2.1.0-SNAPSHOT.zip: https://mobicents.ci.cloudbees.com/job/Mobicents-jSS7-Release-2.x/

Build attempted from master.

**Comment by vetss** [comment]
We made much work fixing on build script.
Please recheck again from master branch
