### ISSUE TITLE
SCCPExecutor not being recognized

### ISSUE THREAD

**Issue by rjcossa** [RestComm/jss7#60]
Hi to all,

I am using the following environment:

JBoss AS 7.1.1.Final "Brontes"
Restcomm version: restcomm-jss7-3.0.1333
**
I get the following error:**

11:18:37,490 WARN  [ShellServer] Received command="sccp set" for which no ShellExecutor is configured

Please note that i have seen the following on the jboss-beans file:

> <bean name="SccpStack" class="org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl">
                <constructor>
                        <parameter>SccpStack</parameter>
                </constructor>
                <property name="persistDir">${jboss.server.data.dir}</property>
                <property name="mtp3UserParts">
                        <map keyClass="java.lang.Integer" valueClass="org.mobicents.protocols.ss7.mtp.Mtp3UserPart">
                                <entry>
                                        <key>1</key>
                                        <value>
                                                <inject bean="Mtp3UserPart" />
                                        </value>
                                </entry>
                        </map>
                </property>
        </bean>

        <bean name="SccpExecutor" class="org.mobicents.protocols.ss7.sccp.impl.oam.SccpExecutor">
                <property name="sccpStacks">
                        <map keyClass="java.lang.String" valueClass="org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl">
                                <entry>
                                        <key>SccpStack</key>
                                        <value>
                                                <inject bean="SccpStack" />
                                        </value>
                                </entry>
                        </map>          
                </property>
        </bean>

>

**Comment by vetss** [comment]
1) JBOSS 5.1 is only supported now
2) try to use config templates from: 
https://github.com/RestComm/jss7/tree/master/service/src/main/config

**Comment by rjcossa** [comment]
Hi vetss, 

Thank you for your very important response, 

One question though, 

Is java 1.7 compatible with this JBoss version because i understand that it is a requirement for the M3UA to work over SCTP. 

Thank you in advance for your response.

**Comment by vetss** [comment]
I am closing this issue
