### ISSUE TITLE
Reoccurence of RuleComparator bug - Infinite loop - java.lang.StackOverflowError

### ISSUE THREAD

**Issue by hubertzegota** [RestComm/jss7#62]
There is reoccurence of the issue described here:
https://www.mail-archive.com/mobicents-all-issues-changes@googlegroups.com/msg18952.html

Can I make a described correction ?

**Comment by vetss** [comment]
I can reproduce the issue by CLI script:

sccp address create 11 82 3 8 0 1 4 1/????
sccp address create 12 82 3 8 0 1 4 2/????
sccp rule create 11 K/K 17 1 8 0 1 4 1/???? solitary 11 origination-type localOriginated
sccp rule create 12 K/K 17 1 8 0 1 4 2/???? solitary 12 origination-type localOriginated

I will check your provided solution and commit (it looks like the update is not bit).

**Comment by vetss** [comment]
Fixed by this provided by cummunity update:
https://github.com/RestComm/jss7/commit/e9cb7d35c706b41eed7de2cb89f76b7bfaffe088

Thanks
