### ISSUE TITLE
standalone instructions are incomplete

### ISSUE THREAD

**Issue by jaroszan** [RestComm/jss7#7]
https://github.com/Mobicents/jss7/wiki/StartSS7asStandalone

Can you please update this section with proper links, commands, code etc?

**Comment by deruelle** [comment]
This should be turned into an asciidoc so that he can be on our documentation main website.

**Comment by vetss** [comment]
Hi @deruelle 

I am postponing it to a next release. This need some time if we want to refactor it into a doc + it is better to make the same for other wiki's for which we want to do the same refactoring.
Other wiki's may be "Dadhi support", "SCTPError", "USSDTestingwithDialogicBoards" and a described by the wiki issuer "StartSS7asStandalone".

**Comment by knosach** [comment]
already implemented, latest user guide you can find [here](http://documentation.telestax.com/core/ss7/SS7_Stack_User_Guide.html#_configuring)
