### ISSUE TITLE
Adding of non regression CI job for performance

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#70]
By the way, do we have any non regression CI job for performance as well ?

Yes, similar to http://ci.telestax.com/job/jSip-7-Performance-UAS/ where we measure the performance of our SIP Stack and use https://github.com/Restcomm/PerfCorder to track the metrics like JVM, CPU usage as well as successful, failed calls, response time, ... 
Do you think we could do something similar for jSS7 ? Jaime Casero can help with PerfCorder setup.
How do you usually test the jSS7 stack for performance and to ensure there is no mem leaks ?

So far we did it with jProfiler + load test tool that we created to load the stack. See https://github.com/RestComm/jss7/tree/master/map/load
This is similar to RestComm Perf Coder interms it can also be started via ant, but there is no statistics gathering or CI Job for that.

Very good. I'm adding Jaime to see how we can merge/reuse this work into/with PerfCorder so it can handle SS7 in addition to SIP and so he can help you guys with PerfCorder integration and ensure non regression of performance into CI jobs as much as possible.
Sergey, please create an issue in the roadmap for that.

**Comment by jaimecasero** [comment]
It would be great to have some stats related to SS7 traffic from client view, similar to the csv file generated from Sipp. This csv file could be digested by perfcorder so we may create SS7 measurement stats, and then Performance goals over it. Things like calls completed, calls failed, and response time are desirable.

Apart from that, Perfcorder is focus in the java server process, so as long as the VM is managable through JMX perfcorder should work out of the box, ill take a look to the script, and come out with a perfcorder version...

**Comment by knosach** [comment]
added csv writer https://github.com/RestComm/jss7/commit/e81829d43bf01206bf6b443ef6f9a0e4d7b7eca8 and created CI job
