### ISSUE TITLE
IstCommandRequest, IstCommandResponse, SetReportingStateRequest and SetReportingStateResponse do not extend CallHandlingMessage

### ISSUE THREAD

**Issue by SummaNetworks** [RestComm/jss7#75]
In MAP Protocol, callhandling service implementation, classes
org.mobicents.protocols.ss7.map.api.service.callhandling.IstCommandResponse,
org.mobicents.protocols.ss7.map.api.service.callhandling.IstCommandRequest,
org.mobicents.protocols.ss7.map.api.service.callhandling.SetReportingStateRequest,
org.mobicents.protocols.ss7.map.api.service.callhandling.SetReportingStateResponse extend Serializable instead of CallHandlingMessage.

**Comment by vetss** [comment]
Hello, thanks for a provided PR - https://github.com/RestComm/jss7/pull/76. I have left seme comments there. 

Please fix mentioned by me remarks and then provide a new pull request for ONE operation, I will check and commit and only then we will be able to go forward.

**Comment by vetss** [comment]
I have committed data from https://github.com/RestComm/jss7/pull/76 pull request and closed it.

**Comment by deruelle** [comment]
@SummaNetworks Thanks. Acknowledged at https://telestax.com/acknowledgements/
@vetss shall this issue be closed ?

**Comment by vetss** [comment]
I am closing the issue, it looks like all is done. Thanks for your help.
