### ISSUE TITLE
Enhance extendibility of TCAP, MAP and CAP stacks and providers

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#79]
Issue short: In order to be able to extend TCAP, CAP and MAP stacks and providers implementation protected constructors have to be introduced and the accessibility of tc listeners in tcap provider has to changed to "protected".

Description: Applications  based on the JSs7 library might need to extend the functionality of the TCAP, CAP or MAP stacks. In order to facilitate proper implementations of a possible extension the main classes have to be "opened up" to allow OO inheritance.

**Comment by vetss** [comment]
Hello @AlerantAppNGIN,

I have started of checking of your updates. I am sorry for some delay but last week I was busy with other work. 

Sime updates looks more or less good for me some of them needs some refactoring. I will comment in issues / pull requests.

Let me cover in this update issues #79 and #81 and pull request #80 and #82.

1) I agree for your needs of usage of extended TCAP, CAP, MAP stacks. Just one question - you created new protected constructors for it. Can you please provide a code example of contstructors of extended TCAP/MAP/CAP stacks how they reuse of the new constructors of TCAP, CAP, MAP stacks. It is better if I can make a look of your idea so we do not have problems in future.

2) NamedTCListener - I agree with this idea but I disagree for implementation of it. The name of the stack is stored into MARStack / CAPStack. No need to add it into MAPProvider / CAPProvider. As for now we do not have a referense form Proviter to Stack bu we can add them (like we have in SCCP stack for example) and just reuse of name from a Stack. Do you have any objections for it ?

If you agree can you please prepare cumulative updates for #79 and #81 (ar sets of commits that I will be able to commit). Please let me know.

**Comment by AlerantAppNGIN** [comment]
Hello Sergey,

You can find an example of the TCAP/MAP/CAP stack/provider extension here:
https://github.com/darmaigabor/IM-SCF/tree/master/imscf-common/src/main/java/org/restcomm/imscf/common/ss7
The purpose of this mod is to enable the use both a MAP and a CAP stack on the top of the same TCAP stack. Briefly: a special tclistener, an instance of TCAPListenerImscfAdapter is registered to the TCAP stack. The TCAPProviderImplImscfWrapper overwrite the add/removeTCListners methods to delegate the calls to the adapter class. The TCAPListenerImscfAdapter manages the registration of TCAP listeners and dispatches the incoming events to the proper TC listener (the listener of the MAP or the CAP stack) according to the ApplicationContext of the corresponding TCAP dialog.
As for remarks #2 and #3 I agree with you. 
I’ll prepare a new commit and if you accept it I’ll update the TCAP-ANSI stack too.
Best Regards,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN,

thanks for your update.

I see how are you going to use your patch results. This looks good for me.

1) usaully MAP and CAP messages are routed to different SSN, but your case suppose some mess of it (MAP and CAP both reuse a same SSN). Is it the real case in your side or you just need some combined lister to listern of many/all SSNs and separate traffic inside?

2) It seems for me better to use "private List<TCListener> tcListeners" (not protected). If we do not have some method like "isTCListenerPresent()" we can add it. But if you insist in protected, I agree for it.

3) Please prepare some cumulative commit which I can cherry pick to my branches (I need to update both master and netty-2 branches now). I have not managed to reuse your update from https://github.com/RestComm/jss7/pull/74 and I needed to create some cululative commit for it. And yes we need it to both TCAP and TCAP-ANSI

4) If you are thinking of congestion control in your code please look at "netty-2" branch. This is a branch that is based onf a master branch and contains netty 4 library reusage and congeston control introduction. May be you can also ruse that staff.

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

can we discuss updates in this issue and #81 ?
I can not still added updates into master branch because of updates have some features that are better to be refactored. If you still need them we need to discuss how to refactor code so we can accept them and they will not breake our logic.

**Comment by AlerantAppNGIN** [comment]
Hello @vetss ,

We found an alternative solution to our original issue which doesn't require any modifications of the JSs7 library. I think we should close this issue without any code changes on the master.
Thank you,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

I also think that it is better to avoid code changing. I am closinf the issue.
