### ISSUE TITLE
Enhance TCAP dialog locking

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#83]
Type: Enhancement
Issue short: Add ActionableReentrantLock feature to TCAP Dialog. Higher layers now are able to execute actions before and after dialog lock/unlock.

Description: In the case of real life transactions locking of multiple resources could be necessary. When handle an incoming or send an outgoing TCAP message the TCAP dialog locking is always be a part of the transaction but there could be other locks that the have to be hold too by the transaction. In order to avoid deadlocks the application has to implement some sort of locking protocol. 
Let see an example of a basic locking protocol: Suppose every transaction knows what locks it needs beforehand. It can acquire all the locks at the beginning and releases them at the end of the transaction. Suppose that there is an ordering of the locks of the system and all transaction of the system is follow this ordering when they try to acquire or release a locks. A possible issue could be using Jss7 library is that when a callback of an application listening on TCAP events get called the TCAP dialog lock has been already locked by the JSs7 stack so the application has no control over the locking mechanism (ordering the lock requisition in this example). 
To support the implementation of locking protocols a new type of lock the ActionableReentrantLock is introduced into TCAP Dialogs and the reentrant locks of DialogImpl is replaced by the new lock. ActionableReentrantLock extends ReentrantLock by the following features:
- ActionableReentrantLock allows to assign a LockAction object to the lock object. LockAction interface defines following callback methods: 
  - doPreLockAction - called before trying to acquire a lock
  - doPostLockAction - called after a lock is acquired
  - doPreUnlockAction - called before a lock is released
  - doPostUnlockAction - called after a lock is released
- ActionableReentrantLock has a new lock method: lockAndTriggerActions and a new unlock method: unlockAndTriggerActions which call the appropriate callbacks of the LockAction object before and after calling the lock or unlock method of the super type

**Comment by vetss** [comment]
Hello @AlerantAppNGIN,

thread locking is some sort a diffcult topic, let's discuss it.

The idea for how we use dialogLock of TCAP Dialog is - there are user originated actions (usually for message sending or dialog closing that is originated by a user) and stack originated operations (triggered by message income from SS7 network or timeout timers). We need so all operations will be atomic and any new operation at TCAP stack waits for all previous operations is over. Also TCAP user must not make any big delays in processing of incoming messages, it must perform long term processing in some other thread in order not to break SS7 stack processing logic.

You say "locking of multiple resources could be necessary". Do you mean that you need to include in this set of "multiple resources" also TCAP Dialog dialogLock ? This is possible also in the current implementing if your transaction does not make delays. If you lock dialogLock then Dialog will not start processing of incoming Dialog messages / timeouts.

"there is an ordering of the locks of the system and all transaction of the system is follow this ordering when they try to acquire or release a locks" - dialogLock of TCAP Dialog is the lowest level of locking. Say when SS7 stack is going to lock dialogLock (after an incoming SS7 message / timeouts) then SS7 stack itself does not hold any other locks and no deadlock is possible. For TCAP application yes - if several TCAP applications want to lock the same Dialog this means that need to care of deadlocks.

1) how are you going to use the introduced functionality? You said that you want to lock some resources in transaction include dialogLock. Do you mean you are going to use them for long time and you need to unlock resourses if a new message from SS7 peer / timeout occurs ?

2) which kind of actions are you going to do in 
void doPreLockAction();
void doPostLockAction();
void doPreUnlockAction();
void doPostUnlockAction();
Some other resourse locking / unlocking ?

3) why have you implemented doPre/PostLock/UnlockAction only for timeoutes and do not for other events?

4) "a callback of an application listening on TCAP events get called the TCAP dialog lock has been already locked by the JSs7 stack so the application has no control over the locking mechanism" - can you please provide extra info - do you mean that dialogLock is locked by TCAP stack (incoming messages / timeout) and TCAP user needs to lock it or you mean TCAP user has locked it for some other reasons and incoming messages / timeout is coming and this may lead a problem.

5) we have also TCAP-ANSI stack. We need to make same update there.

Let's may be discuss this so we sure that the update will not break other logic and we will not break your logic in later updates. If you need we can make soem discussion in chat.

**Comment by AlerantAppNGIN** [comment]
Hello,

I’d like to describe our original issue then I’ll try to answer your questions.
We came across this issue during the implementation of our IM-SCF solutions. Our fork of the RestComm JSs7 project is made to implement this real world project. The IM-SCF is a protocol converter which converts between SS7 and SIP protocols. Using its SIP interface it makes it possible to implement telco IN services.
Here is our stacks from a bottom-up view:
|MSC|, |HLR |< - > |IP/SCTP (Modified RestComm SCTP) – M3UA(JSs7) – SCCP(JSs7) – LWCOMM (our own lightweight messaging protocol over UDP) | - | LWCOMM – SUA (SCCP user adaptation layer part of IM-SCF) – TCAP (JSs7 modified) – MAP/CAP(JSs7) – IM-SCF (the “user application”) - SIP Servlets (RestComm SIP Servlets)| < - > |IN services|
The IM-SCF gets messages by callback events from the CAP/MAP stack, converts them and sends them as SIP messages using SIP Servlets. It also acts the reverse way processing SIP messages (by acting as a SIP servlet) and sends CAP or MAP messages using the JSs7 stack.  
From the point of view of the issue there are three important active elements of the system which can generate events, these are: the telecommunication network, the IN services (including SIP timers) and the TCAP timers. For every call in the IM-SCF there is a corresponding TCAP dialog and SIP application session both of which store state information of that call. When the application reacts to an event originating from any of the above elements, changes to the call state should be restricted to those caused by this event. The processing of other events of this call should wait until the previous event has finished processing in order to see a consistent call state. We guarantee this kind of consistency by coordinating the locks already used by both stacks. We have two locks: the SIP Application session (SAS) lock of the SIP Servlets and the TCAP Dialog lock of the TCAP stack. When IM-SCF logic starts processing an incoming SIP message the SIP servlets has already acquire the SAS lock. If there is a need to send SS7 message the TCAP lock is need to be acquired (done automatically by the stack) too. From the other direction when an incoming SS7 message is processed the JSs7 stack acquire the TCAP lock then in order to send SIP message the SAS lock of the call has to be acquired. As you can see if we don’t coordinate the locking mechanism a deadlock situation can happen. The SAS lock is locked by the servlet container of which IM-SCF logic has no control but it has an interaction point in the SUA layer. Therefore whenever an incoming SS7 message travers trough our SUA layer the IM-SCF code  looks up the SAS context of the message and locks the SAS lock before the TCAP dialog lock is being acquired by the TCAP stack. This ensures that there won’t be any deadlock when an incoming and an outgoing message are processed in parallel in the same call. Our problem is caused by the third actor, the TCAP timer which is encapsulated into the TCAP stack so IM-SCF logic has no control of the locking mechanism it uses.
In summery were in need of a callback mechanism in order to be able to control the locking when TCAP timers executes there logic. This was the reason we came up with this ActionableLock idea. We’d like to give a solution which is general but we also want to minimize the impact to the existing API and implementation. 
And here is how we use this solution:
If you browse the IM-SCF source code and look into the code of the newCall(InitialDPRequest idp, CAPModule module)   method of the CallFactoryBean at https://github.com/darmaigabor/IM-SCF/blob/master/imscf-el/src/main/java/org/restcomm/imscf/el/call/CallFactoryBean.java , you can see that the for every new call an AppSessionLockAction object is registered to the TCAP dialog of the call. In the doPreLockAction method of the AppsessionLockAction the SAS lock is acquired and in the doPostUnlockAction method the SAS lock is released. In our case de doPostLockAction and doPreUnlockAction methods are not used. Those two methods are defined in the LockAction interface only to be more futureproof. 
As for your question #3, we thought through why this solution is chosen. It is like we defined a general functionality then we left half implemented it because it was enough to solve our original issue. So probably it would better and more complete if we use the same lock methods throughout the whole stack. If you choose to use the new un/lockAndTrigger methods everywhere in the stack then we will have to apply some minor changes to our IM-SCF code too but that should be of a problem for us.
As for the poor neglected TCAP-ANSI stack concerns  : I am extracting changes from our original commits and since the TCAP-ANSI stack wasn’t the part of the scope of our original project I didn’t list any changes to it, but we will gladly update every changes to that stack too of course.
If you have any further questions please don’t hesitate to ask.

Best Regards,
Gabor

**Comment by vetss** [comment]
Thanks for a detailed info.

May be the best solution for you is to create some new "locking object / dedicated thread for processing" and does not reuse TCAP + SAS locks. I do not have info for SAS lock but TCAP lock is generally made for usage inside TCAP stack to provide some ordering of processing of incoming / outgoing messages / timeouts and not for long term locking ousude TCAP stack. You can for example setup some message queue / listener that will listern both TCAP originated / SIP originated requests and use of some lock (may be better the dedicated for this call thread that will just process a message after a message from the queue). So the idea is to have some dedicated thread(s) that will process your internal logic and does not take a care of states of TCAP / SIP dialogs. Please comment if you have any reasons that prevents you of usage such way (I am not saying now of cost of implementing).

Your approach does not seem like as a solution that cover all needs (like you care only for Timeouts) but I guess we can accept it if you really need it. Some doubts are that we will possibly need to change the thread model of our stack (I am not very sure it will occure soon or even occur some time). I am thinking of removing of "lock" objects at all but have some pool of threads that will process all events for TCAP dialog (including message sending).

**Comment by vetss** [comment]
Hello @AlerantAppNGIN,

I have created an issue for discussing of TCAP locking design.
https://github.com/RestComm/jss7/issues/110
Feel free to add comments there.

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

can you please comment if ou still need of this way of dialog locking. We need to release soon and need your feedback.

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

can we discuss again your update. Do you still need it ?

**Comment by vetss** [comment]
We are closing an issue because of no response from a user for long time. We will not implement it.
If this functionality is still needed we can discuss it separately.
