### ISSUE TITLE
Adding XML serializing for classes that are subclasses of SubscriberInfoImpl

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#99]
1) We need to implement missed XML serializing for subclasses that are serialized inside SubscriberInfoImpl:
- mobility.subscriberInformation.LocationInformationGPRSImpl
- mobility.subscriberInformation.PSSubscriberStateImpl
- mobility.subscriberInformation.GPRSMSClassImpl
- mobility.subscriberInformation.MNPInfoResImpl

and of their subclasses if needed.

2) We have to add unit tests for XML serializing for following primitives:
- mobility/subscriberInformation/AnyTimeInterrogationResponseImpl.java
- mobility/subscriberInformation/SubscriberInfoImpl.java

This is needed to finish of implementation of serializing of anyTimeInterrogation response. (anyTimeInterrogation request is not covered at all)

**Comment by vetss** [comment]
What is missed

**Comment by knosach** [comment]
closed by commits above
